<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Configlue.Examples.Shared</AssemblyName>
    <RootNamespace>Configlue.Examples.Shared</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/basic/Configlue/Configlue.csproj" />
    <ProjectReference
      Include="../../src/tools/Configlue.Generator/Configlue.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
</Project>
