<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MSBuildTreatAllWarningsAsErrors>true</MSBuildTreatAllWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Configlue.Codecs" />
    <Using Include="Configlue.Migrations" />
    <Using Include="Configlue.Resources" />
    <Using Include="Configlue.Sources" />
    <Using Include="Configlue.Extensibility" />
    <Using Include="Configlue.State" />
    <Using Include="Configlue.Transformers" />
    <ProjectReference Include="../../src/basic/Configlue.Core/Configlue.Core.csproj" />
    <ProjectReference
      Include="../../src/tools/Configlue.Generator/Configlue.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
</Project>
