<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Configlue.Provider.Yaml</AssemblyName>
    <RootNamespace>Configlue.Provider.Yaml</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageDescription>YAML codec for Configlue resources.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Configlue.Abstraction/Configlue.Abstraction.csproj" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>
