using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Reflection;
using System.Text;

namespace Configlue.Extensions.ComponentModel;

/// <summary>
/// Creates generated <c>Observable</c> proxies for Configlue models.
/// </summary>
/// <remarks>
/// The Configlue source generator emits a nested observable proxy for every
/// generated model via the shared SparseFragments emitter. The nested type is
/// usually <c>Observable</c> but is <c>Sparse</c>-prefixed when a model member
/// collides (mirroring the shared <c>ObservableTypeName</c> rule). The adapters
/// in this package locate that type at runtime so that
/// user models do not have to implement <see cref="System.ComponentModel.INotifyPropertyChanged"/>
/// themselves and this package does not need a compile-time reference to user models.
/// When a model has no generated proxy (for example a hand-written fake), the raw model
/// is used instead and only root-level notifications are available.
/// No Configlue-specific duplicate proxy type is introduced; the generated nested
/// type is the single bindable surface. The shared <c>__SparseTarget</c> unwrap
/// member stays inside generated code (used by nested setters) and is not needed
/// here: this adapter only constructs the proxy, never unwraps it.
/// </remarks>
internal static class ConfiglueBindableProxy
{
    private static readonly ConcurrentDictionary<Type, ConstructorInfo?> Constructors = new();

    public static object Create(Type modelType, object value, Action? onChanged)
    {
        var constructor = Constructors.GetOrAdd(modelType, static type => FindConstructor(type));

        if (constructor is null)
        {
            return value;
        }

        return constructor.Invoke(new[] { value, onChanged });
    }

    private static ConstructorInfo? FindConstructor(Type modelType)
    {
        // Mirror the shared ObservableTypeName collision rule: "Observable" unless
        // a member property collides, then "Sparse"-prefixed until free.
        var taken = new HashSet<string>(StringComparer.Ordinal);
        foreach (
            var property in modelType.GetProperties(BindingFlags.Public | BindingFlags.Instance)
        )
        {
            taken.Add(property.Name);
        }

        var builder = new StringBuilder("Observable");
        while (taken.Contains(builder.ToString()))
        {
            builder.Insert(0, "Sparse");
        }

        var candidate = builder.ToString();
        var nested = modelType.GetNestedType(candidate, BindingFlags.Public);
        // Back-compat fallback for proxies generated by the pre-shared local
        // emitter, which always used the fixed name "Observable".
        if (nested is null && !string.Equals(candidate, "Observable", StringComparison.Ordinal))
        {
            nested = modelType.GetNestedType("Observable", BindingFlags.Public);
        }

        return nested?.GetConstructor(new[] { modelType, typeof(Action) });
    }
}
