using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Configlue.Generator;

[Generator(LanguageNames.CSharp)]
public sealed partial class ConfiglueGenerator : IIncrementalGenerator
{
    private const string ModelAttributeName = "Configlue.ConfiglueModelAttribute";
    private const string SecretValueAttributeName = "Configlue.SecretValueAttribute";
    private const string PreviousVersionAttributeName =
        "Configlue.ConfigluePreviousVersionAttribute";
    private const string MergeAttributeName = "Configlue.ConfiglueMergeAttribute";
    private const string EmitIsExternalInitOption = "build_property.ConfiglueEmitIsExternalInit";
    internal const string IsExternalInitHintName = "Configlue.IsExternalInit.g.cs";
    internal const string IsExternalInitSource =
        "// <auto-generated />\n"
        + "#nullable enable\n"
        + "namespace System.Runtime.CompilerServices\n"
        + "{\n"
        + "    internal static partial class IsExternalInit\n"
        + "    {\n"
        + "    }\n"
        + "}\n";
    private const int CustomMergeMode = 4;
    private const int InitialSchemaVersion = 1;

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "CFG001",
        "Configlue model must be partial",
        "Model '{0}' must be declared partial",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedModel = new(
        "CFG002",
        "Unsupported Configlue model",
        "Model '{0}' must be a top-level, non-generic, non-abstract, non-file-local class or struct and cannot be ref-like",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor MissingConstructor = new(
        "CFG003",
        "Model needs a supported constructor",
        "Class model '{0}' must have a parameterless constructor or a constructor whose parameters match public readable properties by name and type; a setter, when present, must be public",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedStructural = new(
        "CFG010",
        "Unsupported structural member construction",
        "Member '{0}' has an unsupported structural type; provide a supported public constructor and properties, decorate it as a fragment model, or explicitly select MergeMode.Replace",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedClone = new(
        "CFG011",
        "Unsupported deep clone member",
        "Member '{0}' has a reference shape that cannot be deeply cloned safely (unsupported type or constructor-bound cycle); use a supported structural type or collection, or explicitly mark a reference-safe property with ConfiglueCloneReferenceSafe",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );

    private static readonly DiagnosticDescriptor UnsupportedRequired = new(
        "CFG004",
        "Required member cannot be constructed",
        "Required member '{0}' must be represented by an accessible public property in the fragment construction plan",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedMerge = new(
        "CFG005",
        "Unsupported merge mode",
        "Merge mode '{0}' is not supported for member '{1}'",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidPreviousVersion = new(
        "CFG006",
        "Invalid Configlue previous version",
        "Previous model '{0}' must declare a distinct lower version with the same schema ID as model '{1}'",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidModelId = new(
        "CFG007",
        "Invalid Configlue model schema ID",
        "Model '{0}' must declare a non-blank schema ID as the first ConfiglueModel attribute argument",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidModelVersion = new(
        "CFG008",
        "Invalid Configlue model schema version",
        "Model '{0}' must declare a schema version of 1 or greater",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidMergeStrategy = new(
        "CFG009",
        "Invalid custom merge strategy",
        "Merge strategy '{0}' is invalid for member '{1}': it must target a non-nested member type and be a concrete type with an accessible parameterless constructor deriving from ConfiglueMergeStrategy<TMember>",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor DuplicateJsonPropertyName = new(
        "CFG012",
        "Duplicate Configlue JSON property name",
        "Member '{0}' duplicates the JSON name of member '{1}'",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor GeneratedNameCollision = new(
        "CFG013",
        "Configlue member conflicts with generated API",
        "Member '{0}' conflicts with a name reserved by the generated Configlue API",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidDependentModel = new(
        "CFG015",
        "Invalid dependent Configlue model",
        "Dependent model '{0}' does not satisfy the Configlue generation contract",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor DuplicateModelIdentity = new(
        "CFG014",
        "Duplicate Configlue schema identity",
        "Model '{0}' duplicates the schema ID and version of model '{1}'",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedMemberType = new(
        "CFG016",
        "Unsupported Configlue member type",
        "Member '{0}' has unsupported type '{1}'; dynamic, pointer, function-pointer, ref-like, and open type-parameter shapes are not supported",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );

    private static readonly DiagnosticDescriptor IncompatiblePromotedModel = new(
        "CFG017",
        "Incompatible promoted Configlue model",
        "Promoted model '{0}' requires incompatible generated semantics from different roots",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );

    private static bool IsExternalInitEmissionEnabled(AnalyzerConfigOptionsProvider options)
    {
        return !options.GlobalOptions.TryGetValue(EmitIsExternalInitOption, out var value)
            || !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);
    }

    internal static bool ShouldEmitIsExternalInit(Compilation compilation, bool configured) =>
        SparseFragments.Generator.Shared.SparseExternalInit.ShouldEmitIsExternalInit(
            compilation,
            configured
        );
}
