using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Configlue.Generator;

public sealed partial class ConfiglueGenerator
{
    private static string BuildSource(
        ModelInfo model,
        ImmutableArray<MemberModel> members,
        ImmutableArray<PreviousModelInfo> previousModels,
        ImmutableArray<PocoCloneModel> pocoCloneModels,
        ImmutableArray<StructuralModel> structuralModels,
        bool hasJsonFragmentRegistry,
        bool hasMessagePackFragmentRegistry,
        bool bclSetSupportsReadOnlySet,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        // The JSON Patch bridge reuses the generated fragment JSON converter as its canonical
        // representation and is now unconditional, so the converter is always emitted.
        // Registry registration and the provider payload-writer interface remain conditional
        // on the JSON provider (see AppendFacadeRuntimeBridge and AppendJsonConverter).
        var modelType = model.ModelTypeName;
        var portableSetView =
            SparseFragments.Generator.Shared.SparseFragmentCoreEmitter.RequiresPortableSetView(
                bclSetSupportsReadOnlySet,
                members
                    .Select(static member => member.Collection.NamedTypeDefinition)
                    .Concat(
                        pocoCloneModels.SelectMany(static poco =>
                            poco.Members.Select(static member =>
                                member.Collection.NamedTypeDefinition
                            )
                        )
                    )
                    .Concat(
                        structuralModels.SelectMany(static structural =>
                            structural.Members.Select(static member =>
                                member.Collection.NamedTypeDefinition
                            )
                        )
                    )
            );
        string generatedType;
        if (model.IsStruct)
        {
            generatedType =
                (model.IsReadOnly ? "readonly " : "")
                + (model.IsRecord ? "partial record struct " : "partial struct ");
        }
        else
        {
            generatedType = model.IsRecord ? "partial record " : "partial class ";
        }
        var name = EscapeIdentifier(model.Name);
        var modelId = model.ModelId;
        var version = model.Version;
        var code = new IndentedStringBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        var hasNamespace = !model.IsGlobalNamespace;
        if (hasNamespace)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine();
            code.AppendLine("{");
            code.IndentOffset++;
        }

        code.Append(generatedType)
            .Append(name)
            .Append(" : global::Configlue.IConfiglueDeepCloneable<")
            .Append(modelType)
            .Append(">, global::Configlue.CompilerServices.IConfiglueModel<")
            .Append(modelType)
            .Append(", ")
            .Append(modelType)
            .Append(".Fragment>, global::Configlue.CompilerServices.IConfiglueFacadeModel<")
            .Append(modelType)
            .AppendLine(">");
        code.AppendLine("{");
        AppendModelSchema(code, modelType, modelId, version, members);
        AppendFragmentSchema(code, modelType, modelId, version, members);
        SparseFragments.Generator.Shared.SparseFragmentCoreEmitter.AppendRootProjectionConstructor(
            code,
            name,
            members.Select(ToSparseMember).ToImmutableArray(),
            model.Constructor
        );
        FragmentCore.AppendDeepClone(
            code,
            modelType,
            members.Select(member => ToSparseMember(member, portableSetView)).ToImmutableArray(),
            !pocoCloneModels.IsEmpty,
            model.Constructor,
            !model.IsStruct
        );
        foreach (var poco in pocoCloneModels)
            FragmentCore.AppendPocoCloneHelper(
                code,
                poco.Model.ModelTypeName,
                poco.CloneHelperName,
                poco.Members.Select(member => ToSparseMember(member, portableSetView))
                    .ToImmutableArray(),
                poco.Model.Constructor
            );
        SparseFragments.Generator.Shared.SparseFragmentCoreEmitter.AppendCollectionCloneHelpers(
            code,
            portableSetView
        );
        AppendFragment(
            code,
            modelType,
            members,
            previousModels,
            !model.IsStruct,
            !pocoCloneModels.IsEmpty,
            hasJsonFragmentRegistry,
            hasMessagePackFragmentRegistry,
            portableSetView: portableSetView,
            constructor: model.Constructor
        );
        AppendDetailsTree(code, modelType, members);
        if (!model.IsStruct)
        {
            AppendObservableModel(code, modelType, true, members);
        }

        AppendStructuralModels(
            code,
            structuralModels,
            !pocoCloneModels.IsEmpty,
            hasJsonFragmentRegistry,
            hasMessagePackFragmentRegistry,
            portableSetView
        );
        AppendFacadeRuntimeBridge(
            code,
            modelType,
            structuralModels,
            hasJsonFragmentRegistry,
            hasMessagePackFragmentRegistry
        );
        AppendHistoricalDispatcherFactory(code, modelType, previousModels);
        code.AppendLine("}");
        AppendTypedPatchExtensions(code, modelType, name, model.IsPublic);
        AppendDetailsExtensions(code, modelType, name, model.IsPublic);
        if (hasNamespace)
        {
            code.IndentOffset--;
            code.AppendLine("}");
        }

        return code.ToString();
    }

    private static void AppendStructuralModels(
        IndentedStringBuilder code,
        ImmutableArray<StructuralModel> structuralModels,
        bool usesPocoCloning,
        bool hasJsonFragmentRegistry,
        bool hasMessagePackFragmentRegistry,
        bool portableSetView
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var structuralModel in structuralModels)
        {
            code.AppendLineAt(
                1,
                "/// <summary>Root-owned generated shape for an undecorated structural configuration type.</summary>"
            );
            code.AppendLineAt(1, "public sealed class " + structuralModel.HostName);
            code.AppendLineAt(1, "{");
            code.IndentOffset++;
            AppendModelSchema(
                code,
                structuralModel.ValueTypeName,
                structuralModel.ValueTypeName,
                InitialSchemaVersion,
                structuralModel.Members
            );
            AppendFragmentSchema(
                code,
                structuralModel.ValueTypeName,
                structuralModel.ValueTypeName,
                InitialSchemaVersion,
                structuralModel.Members
            );
            AppendDetailsTree(code, structuralModel.ValueTypeName, structuralModel.Members);
            AppendObservableModel(
                code,
                structuralModel.ValueTypeName,
                true,
                structuralModel.Members
            );
            AppendFragment(
                code,
                structuralModel.ValueTypeName,
                structuralModel.Members,
                ImmutableArray<PreviousModelInfo>.Empty,
                true,
                usesPocoCloning,
                hasJsonFragmentRegistry,
                hasMessagePackFragmentRegistry,
                portableSetView: portableSetView,
                isRootModel: false,
                constructor: structuralModel.Constructor
            );
            code.IndentOffset--;
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendTypedPatchExtensions(
        IndentedStringBuilder code,
        string modelType,
        string modelName,
        bool isPublic
    )
    {
        var extensionType = modelName + "PatchOptionsExtensions";
        code.AppendLine((isPublic ? "public" : "internal") + " static class " + extensionType);
        code.AppendLine("{");
        code.AppendLineAt(
            1,
            "public static global::System.Threading.Tasks.ValueTask<global::Configlue.StateWriteReceipt> SaveAsync("
        );
        code.AppendLineAt(2, "this global::Configlue.IWritableState<" + modelType + "> options,");
        code.AppendLineAt(2, "global::System.Action<" + modelType + ".Patch> configure,");
        code.AppendLineAt(
            2,
            "global::System.Threading.CancellationToken cancellationToken = default)"
        );
        code.AppendLineAt(1, "{");
        AppendNullGuard(code, 2, "options");
        AppendNullGuard(code, 2, "configure");
        code.AppendLineAt(2, "var patch = new " + modelType + ".Patch();");
        code.AppendLineAt(2, "configure(patch);");
        code.AppendLineAt(2, "return options.SaveAsync(patch, cancellationToken);");
        code.AppendLineAt(1, "}");
        AppendSourcePatchExtension(code, modelType, "SaveAsync", "SaveAsync");
        AppendSourcePatchExtension(code, modelType, "ReplaceAsync", "ReplaceAsync");
        code.AppendLine("}");
    }

    private static void AppendSourcePatchExtension(
        IndentedStringBuilder code,
        string modelType,
        string methodName,
        string handleMethodName
    )
    {
        code.AppendLineAt(
            1,
            "public static global::System.Threading.Tasks.ValueTask<global::Configlue.StateWriteReceipt> "
                + methodName
                + "("
        );
        code.AppendLineAt(
            2,
            "this global::Configlue.ConfiglueSourceHandle<" + modelType + "> source,"
        );
        code.AppendLineAt(2, "global::System.Action<" + modelType + ".Patch> configure,");
        code.AppendLineAt(
            2,
            "global::System.Threading.CancellationToken cancellationToken = default)"
        );
        code.AppendLineAt(1, "{");
        AppendNullGuard(code, 2, "source");
        AppendNullGuard(code, 2, "configure");
        code.AppendLineAt(2, "var patch = new " + modelType + ".Patch();");
        code.AppendLineAt(2, "configure(patch);");
        code.AppendLineAt(2, "return source." + handleMethodName + "(patch, cancellationToken);");
        code.AppendLineAt(1, "}");
    }

    private static void AppendNullGuard(IndentedStringBuilder code, int indent, string variable)
    {
        code.AppendLineAt(indent, "if (" + variable + " is null)");
        code.AppendLineAt(indent, "{");
        code.AppendLineAt(
            indent + 1,
            "throw new global::System.ArgumentNullException(nameof(" + variable + "));"
        );
        code.AppendLineAt(indent, "}");
    }

    private static void AppendHistoricalDispatcherFactory(
        IndentedStringBuilder code,
        string modelType,
        ImmutableArray<PreviousModelInfo> previousModels
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        if (previousModels.IsEmpty)
        {
            return;
        }

        var parameters = new List<string>();
        var parameterDocs = new List<string>();
        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = previousModel.Version;
            var previousType = previousModel.ModelTypeName + ".Fragment";
            var codecName = "previousV" + version + "Codec";
            parameters.Add(
                "global::Configlue.Codecs.IStateCodec<" + previousType + "> " + codecName
            );
            parameterDocs.Add(
                "/// <param name=\""
                    + codecName
                    + "\">The codec for historical schema version "
                    + version
                    + ".</param>"
            );
        }

        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = previousModel.Version;
            var previousType = previousModel.ModelTypeName + ".Fragment";
            var migrationName = "migrateV" + version;
            parameters.Add(
                "global::System.Func<"
                    + previousType
                    + ", "
                    + modelType
                    + ".Fragment>? "
                    + migrationName
                    + " = null"
            );
            parameterDocs.Add(
                "/// <param name=\""
                    + migrationName
                    + "\">An optional custom migration from schema version "
                    + version
                    + "; compatible same-name members are transferred by default.</param>"
            );
        }

        code.AppendLineAt(
            1,
            "/// <summary>Creates a closed, version-aware decoder table for the declared historical fragment types.</summary>"
        );
        foreach (var parameterDoc in parameterDocs)
        {
            code.AppendLineAt(1, parameterDoc);
        }
        var accessibility = previousModels.Any(static previous => !previous.Model.IsPublic)
            ? "internal"
            : "public";
        code.AppendIndent(1)
            .Append(accessibility)
            .Append(" static global::Configlue.Migrations.StateSchemaDispatcher<")
            .Append(modelType)
            .AppendLine(".Fragment> CreateSchemaDispatcher(");
        for (var index = 0; index < parameters.Count; index++)
        {
            code.CancellationToken.ThrowIfCancellationRequested();
            code.AppendLineAt(2, parameters[index] + (index < parameters.Count - 1 ? "," : ""));
        }

        code.AppendLineAt(1, ")");
        code.AppendLineAt(1, "{");
        code.AppendIndent(2)
            .Append("var dispatcher = new global::Configlue.Migrations.StateSchemaDispatcher<")
            .Append(modelType)
            .AppendLine(".Fragment>(ConfiglueSchema.ToMetadata());");
        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = previousModel.Version;
            var previousType = previousModel.ModelTypeName;
            code.AppendIndent(2)
                .Append("dispatcher.Add<")
                .Append(previousType)
                .Append(".Fragment>(")
                .Append(previousType)
                .Append(".FragmentSchema.ToMetadata(), previousV")
                .Append(version)
                .Append("Codec, migrateV")
                .Append(version)
                .Append(" ?? (static value => ")
                .Append(modelType)
                .AppendLine(".Fragment.FromPrevious(value)));");
        }

        code.AppendLineAt(2, "return dispatcher;");
        code.AppendLineAt(1, "}");
    }

    private static void AppendModelSchema(
        IndentedStringBuilder code,
        string modelType,
        string modelId,
        int version,
        ImmutableArray<MemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendIndent(1)
            .Append(
                "public static global::Configlue.ConfiglueModelSchema ConfiglueSchema { get; } = new(typeof("
            )
            .Append(modelType)
            .Append("), ")
            .Append(SymbolDisplay.FormatLiteral(modelId, true))
            .Append(", ")
            .Append(version)
            .AppendLine(", new global::Configlue.ConfiglueMemberSchema[]");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            var environmentVariableName = member.Property.EnvironmentVariableName;
            code.AppendIndent(2)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append((member.ChildModel ?? member.Property.Type).NonNullableName)
                .Append("), global::Configlue.MergeMode.")
                .Append(MergeModeName(member.MergeMode))
                .Append(", static value => ((")
                .Append(modelType)
                .Append(")value).")
                .Append(EscapeIdentifier(member.Property.Name))
                .Append(", ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(member.ChildSchemaType!)
                    .Append(".ConfiglueSchema!");
            }

            code.Append(", ")
                .Append(CollectionValueFactory(member))
                .Append(", ")
                .Append(
                    environmentVariableName is not null
                        ? SymbolDisplay.FormatLiteral(environmentVariableName, true)
                        : "null"
                )
                .Append(", ")
                .Append(
                    member.MergeStrategyType is null
                        ? "null"
                        : "Fragment.__configlue_merge_strategy_" + member.Id
                )
                .Append(", static () => default(")
                .Append(member.Property.Type.Name)
                .Append("))");
            AppendMemberSchemaInitializer(code, member);
            code.AppendLine(",");
        }

        code.AppendLineAt(1, "}, static () => Fragment.Empty);");
    }

    private static void AppendMemberSchemaInitializer(
        IndentedStringBuilder code,
        MemberModel member
    )
    {
        var isSet = member.Collection.Kind == CollectionKind.Set;
        if (!member.IsSecret && !isSet)
        {
            return;
        }

        code.Append(" { ");
        if (member.IsSecret)
        {
            code.Append("IsSecret = true");
            if (isSet)
            {
                code.Append(", ");
            }
        }

        if (isSet)
        {
            code.Append("ContainsElement = static (values, element) => ((")
                .Append(member.Property.Type.Name)
                .Append(")values).Contains((")
                .Append(TypeName(member.Collection.ElementType))
                .Append(")element!)");
        }

        code.Append(" }");
    }

    private static string CollectionValueFactory(MemberModel member)
    {
        if (member.MergeStrategyType is not null || member.MergeMode is not (2 or 3))
        {
            return "null";
        }

        var elementType = TypeName(member.Collection.ElementType);
        var values = $"global::System.Linq.Enumerable.Cast<{elementType}>(values)";
        return member.Collection.Kind switch
        {
            CollectionKind.Array =>
                $"static values => global::System.Linq.Enumerable.ToArray({values})",
            CollectionKind.List =>
                $"static values => new global::System.Collections.Generic.List<{elementType}>({values})",
            CollectionKind.Set =>
                $"static values => new global::System.Collections.Generic.HashSet<{elementType}>({values})",
            _ => "null",
        };
    }

    private static void AppendFragmentSchema(
        IndentedStringBuilder code,
        string modelType,
        string modelId,
        int version,
        ImmutableArray<MemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendIndent(1)
            .Append(
                "public static global::Configlue.ConfiglueModelSchema FragmentSchema { get; } = new(typeof("
            )
            .Append(modelType)
            .Append("), ")
            .Append(SymbolDisplay.FormatLiteral(modelId, true))
            .Append(", ")
            .Append(version)
            .AppendLine(", new global::Configlue.ConfiglueMemberSchema[]");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            var valueType = member.ChildModel is null
                ? member.Property.Type.NonNullableName
                : member.ChildFragmentType!;
            code.AppendIndent(2)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append(valueType)
                .Append("), global::Configlue.MergeMode.")
                .Append(MergeModeName(member.MergeMode))
                .Append(", null, ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(member.ChildSchemaType!)
                    .Append(".FragmentSchema!");
            }

            code.Append(", null, null, ")
                .Append(
                    member.MergeStrategyType is null
                        ? "null"
                        : "Fragment.__configlue_merge_strategy_" + member.Id
                );
            code.Append(", static () => default(").Append(member.Property.Type.Name).Append("))");
            AppendMemberSchemaInitializer(code, member);
            code.AppendLine(",");
        }

        code.AppendLineAt(1, "}, static () => Fragment.Empty);");
    }

    private static void AppendFacadeRuntimeBridge(
        IndentedStringBuilder code,
        string modelType,
        ImmutableArray<StructuralModel> structuralModels,
        bool hasJsonFragmentRegistry,
        bool hasMessagePackFragmentRegistry
    )
    {
        code.AppendLineAt(
            1,
            "internal static readonly global::Configlue.CompilerServices.ConfiglueModelDescriptor<"
                + modelType
                + "> __Descriptor = __CreateConfiglueDescriptor();"
        );
        code.AppendLineAt(
            1,
            "private static global::Configlue.CompilerServices.ConfiglueModelDescriptor<"
                + modelType
                + "> __CreateConfiglueDescriptor()"
        );
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "var descriptor = global::Configlue.CompilerServices.ConfiglueRuntime.Describe<"
                + modelType
                + ", "
                + modelType
                + ".Fragment>(new global::Configlue.CompilerServices.ConfiglueModelOperations<"
                + modelType
                + ", "
                + modelType
                + ".Fragment>(ConfiglueSchema, "
                + modelType
                + ".Fragment.Empty, static value => "
                + modelType
                + ".Fragment.From(value), static (before, after) => "
                + modelType
                + ".Fragment.Diff(before, after), static value => value.ToModel()));"
        );
        code.AppendLineAt(
            2,
            "global::Configlue.CompilerServices.ConfiglueModelDescriptor<"
                + modelType
                + ">.Register(descriptor);"
        );
        if (hasJsonFragmentRegistry)
        {
            code.AppendLineAt(
                2,
                "global::Configlue.Provider.Json.ConfiglueJsonFragmentRegistry<"
                    + modelType
                    + ".Fragment>.Register(new "
                    + modelType
                    + ".Fragment.FragmentJsonConverter());"
            );
        }

        if (hasMessagePackFragmentRegistry)
        {
            code.AppendLineAt(
                2,
                "global::Configlue.Provider.MessagePack.ConfiglueMessagePackFragmentRegistry<"
                    + modelType
                    + ".Fragment>.Register("
                    + modelType
                    + ".Fragment.MessagePackFormatter);"
            );
            foreach (var structuralModel in structuralModels)
            {
                var fragmentType = structuralModel.HostName + ".Fragment";
                code.AppendLineAt(
                    2,
                    "global::Configlue.Provider.MessagePack.ConfiglueMessagePackFragmentRegistry<"
                        + fragmentType
                        + ">.Register("
                        + fragmentType
                        + ".MessagePackFormatter);"
                );
            }
        }

        code.AppendLineAt(2, "return descriptor;");
        code.AppendLineAt(1, "}");
    }
}
