using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace Configlue.Generator;

[Generator(LanguageNames.CSharp)]
public sealed partial class ConfiglueGenerator : IIncrementalGenerator
{
    private const string ModelAttributeName = "Configlue.ConfiglueModelAttribute";
    private const string PreviousVersionAttributeName =
        "Configlue.ConfigluePreviousVersionAttribute";
    private const string MergeAttributeName = "Configlue.ConfiglueMergeAttribute";
    private const string IsExternalInitMetadataName =
        "System.Runtime.CompilerServices.IsExternalInit";
    private const string EmitIsExternalInitOption = "build_property.ConfiglueEmitIsExternalInit";
    internal const string IsExternalInitHintName = "Configlue.IsExternalInit.g.cs";
    internal const string IsExternalInitSource =
        "// <auto-generated />\n"
        + "#nullable enable\n"
        + "namespace System.Runtime.CompilerServices\n"
        + "{\n"
        + "    internal static class IsExternalInit\n"
        + "    {\n"
        + "    }\n"
        + "}\n";
    private const int CustomMergeMode = 4;
    private const int InitialSchemaVersion = 1;
    private static readonly SymbolDisplayFormat TypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
                | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

    private static readonly DiagnosticDescriptor MustBePartial = new(
        "CFG001",
        "Configlue model must be partial",
        "Model '{0}' must be declared partial",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedModel = new(
        "CFG002",
        "Unsupported Configlue model",
        "Model '{0}' must be a top-level, non-generic class or struct",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor MissingConstructor = new(
        "CFG003",
        "Model needs a public parameterless constructor",
        "Class model '{0}' must have a public parameterless constructor",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedRequired = new(
        "CFG004",
        "Required model members are unsupported",
        "Required member '{0}' cannot be omitted from a sparse fragment",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor UnsupportedMerge = new(
        "CFG005",
        "Unsupported merge mode",
        "Merge mode '{0}' is not supported for member '{1}'",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidPreviousVersion = new(
        "CFG006",
        "Invalid Configlue previous version",
        "Previous model '{0}' must declare a distinct lower version with the same schema ID as model '{1}'",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidModelId = new(
        "CFG007",
        "Invalid Configlue model schema ID",
        "Model '{0}' must declare a non-blank schema ID as the first ConfiglueModel attribute argument",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidModelVersion = new(
        "CFG008",
        "Invalid Configlue model schema version",
        "Model '{0}' must declare a schema version of 1 or greater",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );
    private static readonly DiagnosticDescriptor InvalidMergeStrategy = new(
        "CFG009",
        "Invalid custom merge strategy",
        "Merge strategy '{0}' is invalid for member '{1}': it must target a non-nested member type and be a concrete type with an accessible parameterless constructor deriving from ConfiglueMergeStrategy<TMember>",
        "Configlue",
        DiagnosticSeverity.Error,
        true
    );

    private static bool IsExternalInitEmissionEnabled(AnalyzerConfigOptionsProvider options)
    {
        return !options.GlobalOptions.TryGetValue(EmitIsExternalInitOption, out var value)
            || !string.Equals(value, "false", StringComparison.OrdinalIgnoreCase);
    }

    internal static bool ShouldEmitIsExternalInit(Compilation compilation, bool configured)
    {
        if (!configured)
        {
            return false;
        }

        var marker = compilation.GetTypeByMetadataName(IsExternalInitMetadataName);
        if (marker is null)
        {
            return true;
        }

        if (SymbolEqualityComparer.Default.Equals(marker.ContainingAssembly, compilation.Assembly))
        {
            return false;
        }

        return marker.DeclaredAccessibility != Accessibility.Public;
    }
}
