using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Configlue.Generator;

public sealed partial class ConfiglueGenerator
{
    private static string BuildSource(
        ModelInfo model,
        ImmutableArray<MemberModel> members,
        ImmutableArray<PreviousModelInfo> previousModels,
        ImmutableArray<PocoCloneModel> pocoCloneModels,
        ImmutableArray<StructuralModel> structuralModels,
        bool hasJsonFragmentRegistry,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        var modelType = model.ModelTypeName;
        string generatedType;
        if (model.IsStruct)
        {
            generatedType = model.IsRecord ? "partial record struct " : "partial struct ";
        }
        else
        {
            generatedType = model.IsRecord ? "partial record class " : "partial class ";
        }
        var name = EscapeIdentifier(model.Name);
        var modelId = model.ModelId;
        var version = model.Version;
        var code = new IndentedStringBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        if (!model.IsGlobalNamespace)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";");
        }
        code.Append(generatedType)
            .Append(name)
            .Append(" : global::SparseFragments.ISparseDeepCloneable<")
            .Append(modelType)
            .Append(">, global::Configlue.CompilerServices.IConfiglueModel<")
            .Append(modelType)
            .Append(", ")
            .Append(modelType)
            .Append(".Fragment>, global::Configlue.CompilerServices.IConfiglueFacadeModel<")
            .Append(modelType)
            .AppendLine(">");
        code.AppendLine("{");
        AppendModelSchema(code, modelType, modelId, version, members);
        AppendFragmentSchema(code, modelType, modelId, version, members);
        AppendDeepClone(code, modelType, members, !pocoCloneModels.IsEmpty);
        AppendPocoCloneHelpers(code, pocoCloneModels);
        AppendCollectionCloneHelpers(code);
        AppendFragment(
            code,
            modelType,
            members,
            previousModels,
            !model.IsStruct,
            !pocoCloneModels.IsEmpty,
            hasJsonFragmentRegistry
        );
        AppendDetailsTree(code, modelType, members);
        if (!model.IsStruct)
        {
            AppendObservableModel(code, modelType, true, members);
        }

        AppendStructuralModels(
            code,
            structuralModels,
            !pocoCloneModels.IsEmpty,
            hasJsonFragmentRegistry
        );
        AppendFacadeRuntimeBridge(code, modelType);
        AppendHistoricalDispatcherFactory(code, modelType, previousModels);
        code.AppendLine("}");
        AppendModelRegistration(code, modelType, hasJsonFragmentRegistry);
        AppendTypedPatchExtensions(code, modelType, name);
        AppendDetailsExtensions(code, modelType, name);
        return code.ToString();
    }

    private static void AppendStructuralModels(
        IndentedStringBuilder code,
        ImmutableArray<StructuralModel> structuralModels,
        bool usesPocoCloning,
        bool hasJsonFragmentRegistry
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var structuralModel in structuralModels)
        {
            code.AppendLineAt(
                1,
                "/// <summary>Root-owned generated shape for an undecorated structural configuration type.</summary>"
            );
            code.AppendLineAt(1, "public sealed class " + structuralModel.HostName);
            code.AppendLineAt(1, "{");
            code.IndentOffset++;
            AppendModelSchema(
                code,
                structuralModel.ValueTypeName,
                structuralModel.ValueTypeName,
                InitialSchemaVersion,
                structuralModel.Members
            );
            AppendFragmentSchema(
                code,
                structuralModel.ValueTypeName,
                structuralModel.ValueTypeName,
                InitialSchemaVersion,
                structuralModel.Members
            );
            AppendDetailsTree(code, structuralModel.ValueTypeName, structuralModel.Members);
            AppendObservableModel(
                code,
                structuralModel.ValueTypeName,
                true,
                structuralModel.Members
            );
            AppendFragment(
                code,
                structuralModel.ValueTypeName,
                structuralModel.Members,
                ImmutableArray<PreviousModelInfo>.Empty,
                true,
                usesPocoCloning,
                hasJsonFragmentRegistry
            );
            code.IndentOffset--;
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendTypedPatchExtensions(
        IndentedStringBuilder code,
        string modelType,
        string modelName
    )
    {
        var extensionType = modelName + "PatchOptionsExtensions";
        code.AppendLine("public static class " + extensionType);
        code.AppendLine("{");
        code.AppendLineAt(
            1,
            "public static global::System.Threading.Tasks.ValueTask<global::Configlue.StateWriteReceipt> SaveAsync("
        );
        code.AppendLineAt(2, "this global::Configlue.IWritableState<" + modelType + "> options,");
        code.AppendLineAt(2, "global::System.Action<" + modelType + ".Patch> configure,");
        code.AppendLineAt(
            2,
            "global::System.Threading.CancellationToken cancellationToken = default)"
        );
        code.AppendLineAt(1, "{");
        AppendNullGuard(code, 2, "options");
        AppendNullGuard(code, 2, "configure");
        code.AppendLineAt(2, "var patch = new " + modelType + ".Patch();");
        code.AppendLineAt(2, "configure(patch);");
        code.AppendLineAt(2, "return options.SaveAsync(patch, cancellationToken);");
        code.AppendLineAt(1, "}");
        AppendSourcePatchExtension(code, modelType, "SaveAsync", "SaveAsync");
        AppendSourcePatchExtension(code, modelType, "ReplaceAsync", "ReplaceAsync");
        code.AppendLine("}");
    }

    private static void AppendSourcePatchExtension(
        IndentedStringBuilder code,
        string modelType,
        string methodName,
        string handleMethodName
    )
    {
        code.AppendLineAt(
            1,
            "public static global::System.Threading.Tasks.ValueTask<global::Configlue.StateWriteReceipt> "
                + methodName
                + "("
        );
        code.AppendLineAt(
            2,
            "this global::Configlue.ConfiglueSourceHandle<" + modelType + "> source,"
        );
        code.AppendLineAt(2, "global::System.Action<" + modelType + ".Patch> configure,");
        code.AppendLineAt(
            2,
            "global::System.Threading.CancellationToken cancellationToken = default)"
        );
        code.AppendLineAt(1, "{");
        AppendNullGuard(code, 2, "source");
        AppendNullGuard(code, 2, "configure");
        code.AppendLineAt(2, "var patch = new " + modelType + ".Patch();");
        code.AppendLineAt(2, "configure(patch);");
        code.AppendLineAt(2, "return source." + handleMethodName + "(patch, cancellationToken);");
        code.AppendLineAt(1, "}");
    }

    private static void AppendNullGuard(IndentedStringBuilder code, int indent, string variable)
    {
        code.AppendLineAt(indent, "if (" + variable + " is null)");
        code.AppendLineAt(indent, "{");
        code.AppendLineAt(
            indent + 1,
            "throw new global::System.ArgumentNullException(nameof(" + variable + "));"
        );
        code.AppendLineAt(indent, "}");
    }

    private static void AppendCollectionCloneHelpers(IndentedStringBuilder code)
    {
        code.AppendLineAt(
            1,
            "private static global::System.Collections.Concurrent.BlockingCollection<T> __CloneBlockingCollection<T>(global::System.Collections.Concurrent.BlockingCollection<T> original, global::System.Collections.Generic.IEnumerable<T> items)"
        );
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "var queue = new global::System.Collections.Concurrent.ConcurrentQueue<T>(items);"
        );
        code.AppendLineAt(2, "var clone = original.BoundedCapacity > 0");
        code.AppendLineAt(
            3,
            "? new global::System.Collections.Concurrent.BlockingCollection<T>(queue, original.BoundedCapacity)"
        );
        code.AppendLineAt(
            3,
            ": new global::System.Collections.Concurrent.BlockingCollection<T>(queue);"
        );
        code.AppendLineAt(2, "if (original.IsAddingCompleted)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "clone.CompleteAdding();");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(2, "return clone;");
        code.AppendLineAt(1, "}");
    }

    private static void AppendHistoricalDispatcherFactory(
        IndentedStringBuilder code,
        string modelType,
        ImmutableArray<PreviousModelInfo> previousModels
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        if (previousModels.IsEmpty)
        {
            return;
        }

        var parameters = new List<string>();
        var parameterDocs = new List<string>();
        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = previousModel.Version;
            var previousType = previousModel.ModelTypeName + ".Fragment";
            var codecName = "previousV" + version + "Codec";
            parameters.Add(
                "        global::Configlue.Codecs.IStateCodec<" + previousType + "> " + codecName
            );
            parameterDocs.Add(
                "/// <param name=\""
                    + codecName
                    + "\">The codec for historical schema version "
                    + version
                    + ".</param>"
            );
        }

        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = previousModel.Version;
            var previousType = previousModel.ModelTypeName + ".Fragment";
            var migrationName = "migrateV" + version;
            parameters.Add(
                "        global::System.Func<"
                    + previousType
                    + ", "
                    + modelType
                    + ".Fragment>? "
                    + migrationName
                    + " = null"
            );
            parameterDocs.Add(
                "/// <param name=\""
                    + migrationName
                    + "\">An optional custom migration from schema version "
                    + version
                    + "; compatible same-name members are transferred by default.</param>"
            );
        }

        code.AppendLineAt(
            1,
            "/// <summary>Creates a closed, version-aware decoder table for the declared historical fragment types.</summary>"
        );
        foreach (var parameterDoc in parameterDocs)
        {
            code.AppendLineAt(1, parameterDoc);
        }
        var accessibility = previousModels.Any(static previous => !previous.Model.IsPublic)
            ? "internal"
            : "public";
        code.AppendIndent(1)
            .Append(accessibility)
            .Append(" static global::Configlue.Migrations.StateSchemaDispatcher<")
            .Append(modelType)
            .AppendLine(".Fragment> CreateSchemaDispatcher(");
        for (var index = 0; index < parameters.Count; index++)
        {
            code.Append(parameters[index]);
            if (index < parameters.Count - 1)
            {
                code.AppendLine(",");
            }
        }

        code.AppendLineAt(1, ")");
        code.AppendLineAt(1, "{");
        code.AppendIndent(2)
            .Append("var dispatcher = new global::Configlue.Migrations.StateSchemaDispatcher<")
            .Append(modelType)
            .AppendLine(".Fragment>(ConfiglueSchema.ToMetadata());");
        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = previousModel.Version;
            var previousType = previousModel.ModelTypeName;
            code.AppendIndent(2)
                .Append("dispatcher.Add<")
                .Append(previousType)
                .Append(".Fragment>(")
                .Append(previousType)
                .Append(".FragmentSchema.ToMetadata(), previousV")
                .Append(version)
                .Append("Codec, migrateV")
                .Append(version)
                .Append(" ?? (static value => ")
                .Append(modelType)
                .AppendLine(".Fragment.FromPrevious(value)));");
        }

        code.AppendLineAt(2, "return dispatcher;");
        code.AppendLineAt(1, "}");
    }

    private static void AppendModelSchema(
        IndentedStringBuilder code,
        string modelType,
        string modelId,
        int version,
        ImmutableArray<MemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendIndent(1)
            .Append(
                "public static global::Configlue.ConfiglueModelSchema ConfiglueSchema { get; } = new(typeof("
            )
            .Append(modelType)
            .Append("), ")
            .Append(SymbolDisplay.FormatLiteral(modelId, true))
            .Append(", ")
            .Append(version)
            .AppendLine(", new global::Configlue.ConfiglueMemberSchema[]");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            var environmentVariableName = member.Property.EnvironmentVariableName;
            code.AppendIndent(2)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append((member.ChildModel ?? member.Property.Type).NonNullableName)
                .Append("), global::SparseFragments.MergeMode.")
                .Append(MergeModeName(member.MergeMode))
                .Append(", static value => ((")
                .Append(modelType)
                .Append(")value).")
                .Append(EscapeIdentifier(member.Property.Name))
                .Append(", ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(member.ChildSchemaType!)
                    .Append(".ConfiglueSchema!");
            }

            code.Append(", ")
                .Append(CollectionValueFactory(member))
                .Append(", ")
                .Append(
                    environmentVariableName is not null
                        ? SymbolDisplay.FormatLiteral(environmentVariableName, true)
                        : "null"
                )
                .Append(", ")
                .Append(
                    member.MergeStrategyType is null
                        ? "null"
                        : "Fragment.__configlue_merge_strategy_" + member.Id
                )
                .Append(", static () => default(")
                .Append(member.Property.Type.Name)
                .AppendLine(")),");
        }

        code.AppendIndent(1).Append("}, static () => Fragment.Empty);");
    }

    private static string CollectionValueFactory(MemberModel member)
    {
        if (member.MergeStrategyType is not null || member.MergeMode is not (2 or 3))
        {
            return "null";
        }

        var elementType = TypeName(member.Collection.ElementType);
        var values = $"global::System.Linq.Enumerable.Cast<{elementType}>(values)";
        return member.Collection.Kind switch
        {
            CollectionKind.Array =>
                $"static values => global::System.Linq.Enumerable.ToArray({values})",
            CollectionKind.List =>
                $"static values => new global::System.Collections.Generic.List<{elementType}>({values})",
            CollectionKind.Set =>
                $"static values => new global::System.Collections.Generic.HashSet<{elementType}>({values})",
            _ => "null",
        };
    }

    private static void AppendFragmentSchema(
        IndentedStringBuilder code,
        string modelType,
        string modelId,
        int version,
        ImmutableArray<MemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendIndent(1)
            .Append(
                "public static global::Configlue.ConfiglueModelSchema FragmentSchema { get; } = new(typeof("
            )
            .Append(modelType)
            .Append("), ")
            .Append(SymbolDisplay.FormatLiteral(modelId, true))
            .Append(", ")
            .Append(version)
            .AppendLine(", new global::Configlue.ConfiglueMemberSchema[]");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            var valueType = member.ChildModel is null
                ? member.Property.Type.NonNullableName
                : member.ChildFragmentType!;
            code.AppendIndent(2)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append(valueType)
                .Append("), global::SparseFragments.MergeMode.")
                .Append(MergeModeName(member.MergeMode))
                .Append(", null, ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(member.ChildSchemaType!)
                    .Append(".FragmentSchema!");
            }

            code.Append(", null, null, ")
                .Append(
                    member.MergeStrategyType is null
                        ? "null"
                        : "Fragment.__configlue_merge_strategy_" + member.Id
                );
            code.Append(", static () => default(")
                .Append(member.Property.Type.Name)
                .AppendLine(")),");
        }

        code.AppendIndent(1).Append("}, static () => Fragment.Empty);");
    }

    private static void AppendDeepClone(
        IndentedStringBuilder code,
        string modelType,
        ImmutableArray<MemberModel> members,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendIndent(1).Append("public ").Append(modelType).AppendLine(" DeepClone()");
        code.AppendLineAt(1, "{");
        if (usesPocoCloning)
        {
            code.AppendLineAt(
                2,
                "var __configlue_clone_context = new global::System.Collections.Generic.Dictionary<object, object>(global::Configlue.CompilerServices.ConfiglueReferenceEqualityComparer.Instance);"
            );
        }
        code.AppendIndent(2).Append("return new ").Append(modelType).AppendLine();
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            code.AppendIndent(2)
                .Append(EscapeIdentifier(member.Property.Name))
                .Append(" = ")
                .Append(
                    CloneModelExpression(
                        member,
                        "this." + EscapeIdentifier(member.Property.Name),
                        code.CancellationToken
                    )
                )
                .AppendLine(",");
        }

        code.AppendLineAt(1, "};");
        code.AppendLineAt(1, "}");
    }

    private static void AppendPocoCloneHelpers(
        IndentedStringBuilder code,
        ImmutableArray<PocoCloneModel> pocoTypes
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var pocoType in pocoTypes)
        {
            var typeName = pocoType.Model.ModelTypeName;
            code.AppendIndent(1)
                .Append("private static ")
                .Append(typeName)
                .Append(' ')
                .Append(pocoType.CloneHelperName)
                .Append('(')
                .Append(typeName)
                .AppendLine(
                    " value, global::System.Collections.Generic.Dictionary<object, object> __configlue_clone_context)"
                );
            code.AppendLineAt(1, "{");
            code.AppendLineAt(
                2,
                "if (__configlue_clone_context.TryGetValue(value, out var existing)) { return ("
                    + typeName
                    + ")existing; }"
            );
            code.AppendIndent(2).Append("var clone = new ").Append(typeName).AppendLine("();");
            code.AppendLineAt(2, "__configlue_clone_context.Add(value, clone);");
            foreach (var member in pocoType.Members)
            {
                var name = EscapeIdentifier(member.Property.Name);
                code.AppendIndent(2)
                    .Append("clone.")
                    .Append(name)
                    .Append(" = ")
                    .Append(CloneModelExpression(member, "value." + name, code.CancellationToken))
                    .AppendLine(";");
            }
            code.AppendLineAt(2, "return clone;");
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendFacadeRuntimeBridge(IndentedStringBuilder code, string modelType)
    {
        code.AppendLineAt(
            1,
            "internal static readonly global::Configlue.CompilerServices.ConfiglueModelDescriptor<"
                + modelType
                + "> __Descriptor = global::Configlue.CompilerServices.ConfiglueRuntime.Describe<"
                + modelType
                + ", "
                + modelType
                + ".Fragment>(new global::Configlue.CompilerServices.ConfiglueModelOperations<"
                + modelType
                + ", "
                + modelType
                + ".Fragment>(ConfiglueSchema, "
                + modelType
                + ".Fragment.Empty, static value => "
                + modelType
                + ".Fragment.From(value), static (before, after) => "
                + modelType
                + ".Fragment.Diff(before, after), static value => value.ToModel()));"
        );
    }

    private static void AppendModelRegistration(
        IndentedStringBuilder code,
        string modelType,
        bool hasJsonFragmentRegistry
    )
    {
        var registrationType =
            "__ConfiglueRegistration_"
            + string.Concat(modelType.Where(static character => char.IsLetterOrDigit(character)));
        code.AppendLine("internal static class " + registrationType);
        code.AppendLine("{");
        code.AppendLineAt(1, "[global::System.Runtime.CompilerServices.ModuleInitializer]");
        code.AppendLineAt(1, "internal static void Register()");
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "global::Configlue.CompilerServices.ConfiglueModelDescriptor<"
                + modelType
                + ">.Register("
                + modelType
                + ".__Descriptor);"
        );
        if (hasJsonFragmentRegistry)
        {
            code.AppendLineAt(
                2,
                "global::Configlue.Provider.Json.ConfiglueJsonFragmentRegistry<"
                    + modelType
                    + ".Fragment>.Register(new "
                    + modelType
                    + ".Fragment.FragmentJsonConverter());"
            );
        }
        code.AppendLineAt(1, "}");
        code.AppendLine("}");
    }
}
