<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="PublicApiGenerator" Version="11.5.4" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="3.3.1" />
    <PackageReference
      Include="Microsoft.CodeAnalysis.CSharp"
      Version="4.11.0"
      PrivateAssets="all"
    />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/basic/Configlue.Abstraction/Configlue.Abstraction.csproj" />
    <ProjectReference Include="../../src/basic/Configlue.Core/Configlue.Core.csproj" />
    <ProjectReference Include="../../src/extensions/Configlue.Extensions.ComponentModel/Configlue.Extensions.ComponentModel.csproj" />
    <ProjectReference Include="../../src/extensions/Configlue.Extensions.DI/Configlue.Extensions.DI.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.AspNetCore/Configlue.Hosting.AspNetCore.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.Blazor/Configlue.Hosting.Blazor.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.Avalonia/Configlue.Hosting.Avalonia.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.Maui/Configlue.Hosting.Maui.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.Godot/Configlue.Hosting.Godot.csproj" />
    <ProjectReference Include="../../src/extensions/Configlue.Extensions.MSOptions/Configlue.Extensions.MSOptions.csproj" />
    <ProjectReference Include="../../src/extensions/Configlue.Extensions.R3/Configlue.Extensions.R3.csproj" />
    <ProjectReference Include="../../src/providers/Configlue.Provider.Json/Configlue.Provider.Json.csproj" />
    <ProjectReference Include="../../src/providers/Configlue.Provider.MessagePack/Configlue.Provider.MessagePack.csproj" />
    <ProjectReference Include="../../src/providers/Configlue.Provider.Xml/Configlue.Provider.Xml.csproj" />
    <ProjectReference Include="../../src/providers/Configlue.Provider.Yaml/Configlue.Provider.Yaml.csproj" />
    <ProjectReference Include="../../src/sources/Configlue.Source.Environment/Configlue.Source.Environment.csproj" />
    <ProjectReference Include="../../src/sources/Configlue.Source.CommandLine/Configlue.Source.CommandLine.csproj" />
    <ProjectReference Include="../../src/resources/Configlue.Resource.S3/Configlue.Resource.S3.csproj" />
    <ProjectReference Include="../../src/sources/Configlue.Source.Http/Configlue.Source.Http.csproj" />
    <ProjectReference Include="../../src/sources/Configlue.Source.PostgreSql/Configlue.Source.PostgreSql.csproj" />
    <ProjectReference Include="../../src/sources/Configlue.Source.Consul/Configlue.Source.Consul.csproj" />
    <ProjectReference Include="../../src/sources/Configlue.Source.PostgreSql.Migrations/Configlue.Source.PostgreSql.Migrations.csproj" />
    <ProjectReference Include="../../src/resources/Configlue.Resource.Redis/Configlue.Resource.Redis.csproj" />
    <ProjectReference Include="../../src/resources/Configlue.Resource.Vault/Configlue.Resource.Vault.csproj" />
    <ProjectReference Include="../../src/basic/Configlue.Testing/Configlue.Testing.csproj" />
    <ProjectReference Include="../../src/transformers/Configlue.Transformer.AES/Configlue.Transformer.AES.csproj" />
    <ProjectReference Include="../../src/transformers/Configlue.Transformer.Compression/Configlue.Transformer.Compression.csproj" />
    <ProjectReference Include="../../src/tools/Configlue.Generator/Configlue.Generator.csproj" />
    <ProjectReference Include="../../src/fragments/SparseFragments/SparseFragments.csproj" />
    <ProjectReference Include="../../src/fragments/SparseFragments.Generator/SparseFragments.Generator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Approvals/**/*.approved.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
