using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SparseFragments.Generator.Shared;

/// <summary>Builds standalone generated source for a <c>[SparseFragmentModel]</c>.</summary>
internal static class SparseFragmentEmitter
{
    private const string Runtime = SparseWellKnownNames.RuntimeNamespace;
    private const string Optional = SparseWellKnownNames.OptionalType;
    private const string FragmentMember = SparseWellKnownNames.FragmentMemberType;
    private const string FragmentInterface = SparseWellKnownNames.FragmentInterfaceType;
    private const string FragmentOfT = SparseWellKnownNames.FragmentInterfaceType;
    private const string DeepCloneable = SparseWellKnownNames.DeepCloneableType;
    private const string Schema = SparseWellKnownNames.SchemaType;
    private const string MemberSchema = SparseWellKnownNames.MemberSchemaType;
    private const string MergeStrategy = SparseWellKnownNames.MergeStrategyType;
    private const string ReferenceComparer = SparseWellKnownNames.ReferenceComparerType;

    public static string BuildSource(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        ImmutableArray<SparsePocoCloneModel> pocoCloneModels,
        ImmutableArray<SparseStructuralModel> structuralModels,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        var modelType = model.ModelTypeName;
        var generatedType = ModelDeclarationKeyword(model);
        var name = SparseNaming.EscapeIdentifier(model.Name);
        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        if (!model.IsGlobalNamespace)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";");
        }

        code.Append(generatedType)
            .Append(name)
            .Append(" : ")
            .Append(DeepCloneable)
            .Append("<")
            .Append(modelType)
            .AppendLine(">");
        code.AppendLine("{");
        AppendDeepClone(code, modelType, members, !pocoCloneModels.IsEmpty);
        AppendPocoCloneHelpers(code, pocoCloneModels);
        AppendCollectionCloneHelpers(code);
        AppendFragment(code, modelType, members, !model.IsStruct, !pocoCloneModels.IsEmpty);
        AppendStructuralModels(code, structuralModels, !pocoCloneModels.IsEmpty);
        code.AppendLine("}");
        return code.ToString();
    }

    private static string ModelDeclarationKeyword(SparseModelInfo model)
    {
        if (model.IsStruct)
        {
            return model.IsRecord ? "partial record struct " : "partial struct ";
        }

        return model.IsRecord ? "partial record class " : "partial class ";
    }

    private static void AppendStructuralModels(
        SharedIndentedBuilder code,
        ImmutableArray<SparseStructuralModel> structuralModels,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var structuralModel in structuralModels)
        {
            code.AppendLineAt(
                1,
                "/// <summary>Generated shape for an undecorated structural member type.</summary>"
            );
            code.AppendLineAt(1, "public sealed class " + structuralModel.HostName);
            code.AppendLineAt(1, "{");
            code.IndentOffset++;
            AppendFragment(
                code,
                structuralModel.ValueTypeName,
                structuralModel.Members,
                true,
                usesPocoCloning
            );
            code.IndentOffset--;
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendCollectionCloneHelpers(SharedIndentedBuilder code)
    {
        code.AppendLineAt(
            1,
            "private static global::System.Collections.Concurrent.BlockingCollection<T> __CloneBlockingCollection<T>(global::System.Collections.Concurrent.BlockingCollection<T> original, global::System.Collections.Generic.IEnumerable<T> items)"
        );
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "var queue = new global::System.Collections.Concurrent.ConcurrentQueue<T>(items);"
        );
        code.AppendLineAt(2, "var clone = original.BoundedCapacity > 0");
        code.AppendLineAt(
            3,
            "? new global::System.Collections.Concurrent.BlockingCollection<T>(queue, original.BoundedCapacity)"
        );
        code.AppendLineAt(
            3,
            ": new global::System.Collections.Concurrent.BlockingCollection<T>(queue);"
        );
        code.AppendLineAt(2, "if (original.IsAddingCompleted)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "clone.CompleteAdding();");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(2, "return clone;");
        code.AppendLineAt(1, "}");
    }

    private static void AppendDeepClone(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendIndent(1).Append("public ").Append(modelType).AppendLine(" DeepClone()");
        code.AppendLineAt(1, "{");
        if (usesPocoCloning)
        {
            AppendCloneContext(code, 2);
        }

        code.AppendIndent(2).Append("return new ").Append(modelType).AppendLine();
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            code.AppendIndent(2)
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .Append(" = ")
                .Append(
                    Expressions.CloneModelExpression(
                        member,
                        "this." + SparseNaming.EscapeIdentifier(member.Property.Name)
                    )
                )
                .AppendLine(",");
        }

        code.AppendLineAt(1, "};");
        code.AppendLineAt(1, "}");
    }

    private static void AppendPocoCloneHelpers(
        SharedIndentedBuilder code,
        ImmutableArray<SparsePocoCloneModel> pocoTypes
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var pocoType in pocoTypes)
        {
            var typeName = pocoType.Model.ModelTypeName;
            code.AppendIndent(1)
                .Append("private static ")
                .Append(typeName)
                .Append(' ')
                .Append(pocoType.CloneHelperName)
                .Append('(')
                .Append(typeName)
                .AppendLine(
                    " value, global::System.Collections.Generic.Dictionary<object, object> __sparse_clone_context)"
                );
            code.AppendLineAt(1, "{");
            code.AppendLineAt(
                2,
                "if (__sparse_clone_context.TryGetValue(value, out var existing)) { return ("
                    + typeName
                    + ")existing; }"
            );
            code.AppendIndent(2).Append("var clone = new ").Append(typeName).AppendLine("();");
            code.AppendLineAt(2, "__sparse_clone_context.Add(value, clone);");
            foreach (var member in pocoType.Members)
            {
                var memberName = SparseNaming.EscapeIdentifier(member.Property.Name);
                code.AppendIndent(2)
                    .Append("clone.")
                    .Append(memberName)
                    .Append(" = ")
                    .Append(Expressions.CloneModelExpression(member, "value." + memberName))
                    .AppendLine(";");
            }

            code.AppendLineAt(2, "return clone;");
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendCloneContext(SharedIndentedBuilder code, int indent)
    {
        code.AppendIndent(indent)
            .Append(
                "var __sparse_clone_context = new global::System.Collections.Generic.Dictionary<object, object>("
            )
            .Append(ReferenceComparer)
            .AppendLine(".Instance);");
    }

    private static void AppendFragment(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool modelIsReferenceType,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendLineAt(
            1,
            "/// <summary>A sparse, presence-aware representation of this model.</summary>"
        );
        code.AppendLineAt(
            1,
            "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        code.AppendIndent(1)
            .Append("public sealed class Fragment : ")
            .Append(FragmentOfT)
            .Append("<Fragment>, ")
            .Append(DeepCloneable)
            .AppendLine("<Fragment>");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            code.AppendIndent(2)
                .Append("public ")
                .Append(Optional)
                .Append("<")
                .Append(FragmentValueType(member))
                .Append("> ")
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .AppendLine(" { get; init; }");
        }

        foreach (var member in members.Where(static member => member.MergeStrategyType is not null))
        {
            code.AppendIndent(2)
                .Append("internal static readonly ")
                .Append(MergeStrategy)
                .Append("<")
                .Append(member.Property.Type.Name)
                .Append("> ")
                .Append(MergeStrategyField(member))
                .Append(" = new ")
                .Append(member.MergeStrategyType!.Value.Name)
                .AppendLine("();");
        }

        code.AppendLine();
        code.AppendLineAt(
            2,
            "/// <summary>Whether this fragment has no present members.</summary>"
        );
        code.AppendIndent(2)
            .Append("public bool IsEmpty => ")
            .Append(
                members.Length == 0
                    ? "true"
                    : string.Join(
                        " && ",
                        members.Select(member =>
                            "!" + SparseNaming.EscapeIdentifier(member.Property.Name) + ".IsPresent"
                        )
                    )
            )
            .AppendLine(";");
        code.AppendLine();
        AppendFragmentDescriptor(code, modelType, members);
        Core.AppendFromModel(code, modelType, members, modelIsReferenceType, usesPocoCloning);
        SparseFragmentCoreEmitter.AppendToModel(code, modelType, members);
        Core.AppendMerge(code, members);
        Core.AppendApplyChanges(code, members);
        Core.AppendDiff(code, modelType, members, modelIsReferenceType);
        Core.AppendFragmentClone(code, members, usesPocoCloning);
        code.AppendLineAt(1, "}");
    }

    private static void AppendFragmentDescriptor(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendLineAt(2, "/// <summary>The empty fragment.</summary>");
        code.AppendLineAt(2, "public static Fragment Empty { get; } = new();");
        code.AppendIndent(2)
            .Append("public static ")
            .Append(Schema)
            .Append(" FragmentSchema { get; } = new(typeof(")
            .Append(modelType)
            .AppendLine("), new " + MemberSchema + "[]");
        code.AppendLineAt(2, "{");
        foreach (var member in members)
        {
            var valueType = member.ChildModel is null
                ? member.Property.Type.NonNullableName
                : member.ChildFragmentType!;
            code.AppendIndent(3)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append(valueType)
                .Append("), ")
                .Append(Runtime)
                .Append(".MergeMode.")
                .Append(SparseNaming.MergeModeName(member.MergeMode))
                .Append(", static value => ((")
                .Append(modelType)
                .Append(")value).")
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .Append(", ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(member.ChildFragmentType!)
                    .Append(".FragmentSchema");
            }

            code.Append(", ")
                .Append(member.MergeStrategyType is null ? "null" : MergeStrategyField(member))
                .Append(", static () => default(")
                .Append(member.Property.Type.Name)
                .AppendLine(")),");
        }

        code.AppendLineAt(2, "}, static () => Fragment.Empty);");
        code.AppendIndent(2)
            .Append("public ")
            .Append(Schema)
            .AppendLine(" Schema => FragmentSchema;");
        code.AppendLineAt(
            2,
            "public global::System.Collections.Generic.IEnumerable<"
                + FragmentMember
                + "> EnumeratePresentMembers()"
        );
        code.AppendLineAt(2, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(3)
                .Append("if (")
                .Append(name)
                .Append(".IsPresent) yield return new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", ")
                .Append(name)
                .AppendLine(".Value);");
        }

        code.AppendLineAt(2, "}");
        AppendWithMember(code, members);
        AppendWithoutMember(code, members);
        code.AppendLine();
    }

    private static void AppendWithMember(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendIndent(2)
            .Append("public ")
            .Append(FragmentInterface)
            .AppendLine(" WithMember(int memberId, object? value)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "switch (memberId)");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(4).Append("case ").Append(member.Id).AppendLine(":");
            code.AppendIndent(5).Append("return new Fragment");
            code.AppendLine();
            code.AppendLineAt(5, "{");
            foreach (var copy in members)
            {
                var copyName = SparseNaming.EscapeIdentifier(copy.Property.Name);
                code.AppendIndent(6)
                    .Append(copyName)
                    .Append(" = ")
                    .Append(
                        copyName == name
                            ? Optional
                                + "<"
                                + FragmentValueType(copy)
                                + ">.Present(("
                                + FragmentValueType(copy)
                                + ")value!)"
                            : "this." + copyName
                    )
                    .AppendLine(",");
            }

            code.AppendLineAt(5, "};");
        }

        code.AppendLineAt(
            4,
            "default: throw new global::System.ArgumentOutOfRangeException(nameof(memberId));"
        );
        code.AppendLineAt(3, "}");
        code.AppendLineAt(2, "}");
    }

    private static void AppendWithoutMember(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendIndent(2)
            .Append("public ")
            .Append(FragmentInterface)
            .AppendLine(" WithoutMember(int memberId)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "switch (memberId)");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(4).Append("case ").Append(member.Id).AppendLine(":");
            code.AppendIndent(5).Append("return new Fragment");
            code.AppendLine();
            code.AppendLineAt(5, "{");
            foreach (var copy in members)
            {
                var copyName = SparseNaming.EscapeIdentifier(copy.Property.Name);
                code.AppendIndent(6)
                    .Append(copyName)
                    .Append(" = ")
                    .Append(copyName == name ? "default" : "this." + copyName)
                    .AppendLine(",");
            }

            code.AppendLineAt(5, "};");
        }

        code.AppendLineAt(
            4,
            "default: throw new global::System.ArgumentOutOfRangeException(nameof(memberId));"
        );
        code.AppendLineAt(3, "}");
        code.AppendLineAt(2, "}");
    }

    private static string FragmentValueType(SparseMemberModel member) =>
        member.ChildModel is null ? member.Property.Type.Name : member.ChildFragmentType + "?";

    private static string MergeStrategyField(SparseMemberModel member) =>
        SparseWellKnownNames.MergeStrategyFieldPrefix + member.Id;

    private static readonly SparseFragmentExpressions Expressions = new("__sparse_clone_context");

    private static readonly SparseFragmentCoreEmitter Core = new(
        Optional,
        SparseWellKnownNames.MergeStrategyFieldPrefix,
        "__sparse_clone_context",
        ReferenceComparer,
        Expressions
    );
}
