<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48;net10.0</TargetFrameworks>
    <OutputType Condition="'$(TargetFramework)' != 'netstandard2.0'">Exe</OutputType>
    <IsTestProject>false</IsTestProject>
    <RuntimeIdentifiers Condition="'$(OS)' == 'Windows_NT'">win-x86</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Remove="TUnit;Shouldly" />
    <Using Remove="Shouldly;Configlue.Codecs;Configlue.Migrations;Configlue.Resources;Configlue.Sources;Configlue.Extensibility;Configlue.State;Configlue.Transformers" />
    <ProjectReference Include="../../../../src/basic/Configlue.Abstraction/Configlue.Abstraction.csproj" />
    <ProjectReference Include="../../../../src/basic/Configlue.Core/Configlue.Core.csproj" />
    <ProjectReference Include="../../../../src/tools/Configlue.Generator/Configlue.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../../../src/fragments/SparseFragments/SparseFragments.csproj" />
    <ProjectReference Include="../../../../src/fragments/SparseFragments.Generator/SparseFragments.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
