<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Configlue.Testing</AssemblyName>
    <RootNamespace>Configlue.Testing</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageDescription>Test doubles and in-memory resources for Configlue.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Configlue.Abstraction/Configlue.Abstraction.csproj" />
    <ProjectReference Include="../Configlue.Extensibility/Configlue.Extensibility.csproj" />
  </ItemGroup>
</Project>
