<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Configlue.Source.Presets.Yaml</AssemblyName>
    <RootNamespace>Configlue.Source.Presets</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageDescription>YAML file source integration for Configlue common source presets.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Configlue.Provider.Yaml/Configlue.Provider.Yaml.csproj" />
    <ProjectReference Include="../Configlue.Source.Presets/Configlue.Source.Presets.csproj" />
  </ItemGroup>
</Project>
