<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ConfiglueNetStandard>true</ConfiglueNetStandard>
    <IsPackable>false</IsPackable>
    <AssemblyName>PackageSparse.NetStandard.Consumer</AssemblyName>
  </PropertyGroup>
  <ItemGroup Condition="'$(ConfigluePackageVersion)' == ''">
    <ProjectReference Include="../../../../src/fragments/SparseFragments/SparseFragments.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(ConfigluePackageVersion)' != ''">
    <PackageReference Include="SparseFragments" Version="$(ConfigluePackageVersion)" />
  </ItemGroup>
</Project>
