<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Configlue.Resource.Http.AspNetCore</AssemblyName>
    <RootNamespace>Configlue.Resource.Http.AspNetCore</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageDescription>ASP.NET Core HTTP endpoints for Configlue resources.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Configlue.Resource.Http/Configlue.Resource.Http.csproj" />
  </ItemGroup>
</Project>
