using System.Buffers;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using Configlue.CompilerServices;
using Configlue.DocumentEditing;
using SharpYaml;
using SharpYaml.Events;
using SharpYaml.Model;

namespace Configlue.Provider.Yaml;

internal static class YamlDocumentEditor
{
    private static readonly UTF8Encoding StrictUtf8 = new(
        encoderShouldEmitUTF8Identifier: false,
        throwOnInvalidBytes: true
    );

    internal static byte[] Update(
        ReadOnlyMemory<byte> current,
        ReadOnlyMemory<byte> updated,
        IReadOnlyList<string> path,
        ReadOnlyMemory<byte> schemaShape,
        Encoding? textEncoding
    )
    {
        return Update(current, updated, path, schemaShape, null, textEncoding);
    }

    internal static byte[] Update(
        ReadOnlyMemory<byte> current,
        ReadOnlyMemory<byte> updated,
        IReadOnlyList<string> path,
        ReadOnlyMemory<byte> legacySchemaShape,
        YamlSchemaShape? schemaShape,
        Encoding? textEncoding
    )
    {
        var currentText = current.IsEmpty ? "" : Decode(current, textEncoding);
        var updatedText = Decode(updated, textEncoding);
        var newline = FindNewline(currentText);
        var currentDocument = YamlTextDocument.Parse(currentText);
        var updatedDocument = YamlTextDocument.Parse(updatedText);
        // The schema shape is generated by CreateSchemaShape in the same textEncoding as the
        // document buffers, so it must be decoded with that encoding (not hard-coded UTF-8).
        var shapeEncoding = textEncoding;
        YamlTextNode? shapeRoot = null;
        ConfiglueModelSchema? shapeSchema = null;
        if (schemaShape is not null)
        {
            shapeRoot = schemaShape.RootNode;
            shapeSchema = schemaShape.RootSchema;
        }
        else if (!legacySchemaShape.IsEmpty)
        {
            shapeRoot = YamlTextDocument.Parse(Decode(legacySchemaShape, shapeEncoding)).Root;
        }

        var editor = new Editor(currentDocument, schemaShape);

        if (path.Count == 0)
        {
            editor.AddDiff(
                currentDocument.Root,
                updatedDocument.Root,
                shapeRoot,
                null,
                null,
                shapeSchema
            );
        }
        else
        {
            var section = currentDocument.GetPath(path);
            if (section is not null)
            {
                editor.AddDiff(section, updatedDocument.Root, shapeRoot, null, null, shapeSchema);
            }
            else
            {
                var parentLength = path.Count - 1;
                YamlTextNode? parent = null;
                while (parentLength >= 0)
                {
                    parent = currentDocument.GetPath(path.Take(parentLength).ToArray());
                    if (parent is not null)
                    {
                        break;
                    }

                    parentLength--;
                }

                if (parent is null || parent.Kind != YamlTextKind.Mapping)
                {
                    throw new YamlException(
                        $"YAML section path '{string.Join(":", path)}' has no containing mapping."
                    );
                }

                var wrapped = updatedText[updatedDocument.Root.Start..updatedDocument.Root.End];
                for (var index = path.Count - 1; index > parentLength; index--)
                {
                    wrapped = WrapProperty(path[index], wrapped, newline);
                }

                editor.AddPropertyAtPath(parent, path[parentLength], wrapped);
            }
        }

        var originalPreamble = textEncoding?.GetPreamble() ?? [];
        var preservePreamble =
            originalPreamble.Length > 0 && current.Span.StartsWith(originalPreamble);
        return Encode(editor.ApplyEdits(), textEncoding, originalPreamble, preservePreamble);
    }

    internal static byte[] CreateSchemaShape(
        ConfiglueModelSchema schema,
        JsonNamingPolicy? namingPolicy,
        YamlSerializerOptions? serializerOptions,
        DocumentLayoutOptions? layout,
        Encoding? textEncoding = null
    )
    {
        var fragment = DocumentSemanticEditPlan.CreateShallowPresentFragment(schema);
        var codec = new YamlStateCodec(
            namingPolicy,
            schema,
            serializerOptions,
            layout,
            textEncoding
        );
        var buffer = new ArrayBufferWriter<byte>();
        codec.Serialize(
            fragment.GetType(),
            fragment,
            buffer,
            new StateCodecContext(schema.ToMetadata(), null, null)
        );
        return buffer.WrittenSpan.ToArray();
    }

    private static string WrapProperty(string name, string value, string newline)
    {
        var key = YamlSerializer.Serialize(name).TrimEnd('\r', '\n');
        return key + ":" + newline + Indent(value, "  ", newline);
    }

    private static string Decode(ReadOnlyMemory<byte> content, Encoding? textEncoding)
    {
        string text;
        if (textEncoding is null)
        {
            text = StrictUtf8.GetString(content.ToArray());
        }
        else
        {
            using var stream = CreateReadOnlyStream(content);
            using var reader = new StreamReader(
                stream,
                textEncoding,
                detectEncodingFromByteOrderMarks: true
            );
            text = reader.ReadToEnd();
        }

        return text.Length > 0 && text[0] == '\uFEFF' ? text.Substring(1) : text;
    }

    private static MemoryStream CreateReadOnlyStream(ReadOnlyMemory<byte> content)
    {
        if (MemoryMarshal.TryGetArray(content, out var segment) && segment.Array is not null)
        {
            return new MemoryStream(segment.Array, segment.Offset, segment.Count, writable: false);
        }

        return new MemoryStream(content.ToArray(), writable: false);
    }

    private static byte[] Encode(
        string text,
        Encoding? textEncoding,
        byte[] preamble,
        bool preservePreamble
    )
    {
        var encoded = (textEncoding ?? Encoding.UTF8).GetBytes(text);
        if (!preservePreamble)
        {
            return encoded;
        }

        var result = new byte[preamble.Length + encoded.Length];
        preamble.CopyTo(result, 0);
        encoded.CopyTo(result, preamble.Length);
        return result;
    }

    private static string Indent(string text, string indentation, string newline)
    {
        var lines = text.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
        return string.Join(
            newline,
            lines.Select(line => line.Length == 0 ? line : indentation + line)
        );
    }

    private static string FindNewline(string source)
    {
        var index = source.IndexOf('\n');
        if (index > 0 && source[index - 1] == '\r')
        {
            return "\r\n";
        }

        return index >= 0 ? "\n" : Environment.NewLine;
    }

    private sealed class Editor(YamlTextDocument document, YamlSchemaShape? schemaShape = null)
    {
        private readonly List<TextEdit> _edits = [];
        private readonly HashSet<int> _removedFlowCommas = [];
        private readonly YamlSchemaShape? _schemaShape = schemaShape;
        private string Newline => FindNewline(document.Source);

        internal void AddDiff(
            YamlTextNode current,
            YamlTextNode updated,
            YamlTextNode? shape,
            YamlTextProperty? currentProperty = null,
            YamlTextProperty? updatedProperty = null,
            ConfiglueModelSchema? currentSchema = null
        )
        {
            if (current.Kind != updated.Kind)
            {
                AddReplacement(current, updated, currentProperty, updatedProperty);
                return;
            }

            switch (current.Kind)
            {
                case YamlTextKind.Mapping:
                    AddMappingDiff(current, updated, shape, currentSchema);
                    break;
                case YamlTextKind.Sequence:
                    AddSequenceDiff(current, updated, currentSchema);
                    break;
                case YamlTextKind.Scalar:
                    if (!Equivalent(current, updated))
                    {
                        AddReplacement(current, updated, currentProperty, updatedProperty);
                    }

                    break;
                default:
                    throw new YamlException("The YAML document contains an unsupported node.");
            }
        }

        internal void AddPropertyAtPath(YamlTextNode parent, string name, string value)
        {
            if (parent.Kind != YamlTextKind.Mapping)
            {
                throw new YamlException("A YAML section's containing value must be a mapping.");
            }

            AddProperties(parent, [WrapProperty(name, value, Newline)], parent.Properties!);
        }

        internal string ApplyEdits()
        {
            var result = document.Source;
            foreach (var edit in _edits.OrderByDescending(static edit => edit.Start))
            {
                result =
                    result.Substring(0, edit.Start)
                    + edit.Content
                    + result.Substring(edit.Start + edit.Length);
            }

            return result;
        }

        private void AddMappingDiff(
            YamlTextNode current,
            YamlTextNode updated,
            YamlTextNode? shape,
            ConfiglueModelSchema? currentSchema = null
        )
        {
            var currentProperties = current.Properties!;
            var updatedProperties = updated.Properties!;
            var shapeByName = shape?.Properties?.ToDictionary(
                static property => property.Name,
                StringComparer.Ordinal
            );
            var shapeNames = shapeByName is null
                ? null
                : new HashSet<string>(shapeByName.Keys, StringComparer.Ordinal);

            var isFlow = ((YamlMapping)current.Element).Style == YamlStyle.Flow;
            DocumentSemanticEditPlan.DiffObjects(
                currentProperties.Select(static property => property.Name).ToArray(),
                updatedProperties.Select(static property => property.Name).ToArray(),
                shapeNames,
                _schemaShape is not null,
                onRemove: currentIndex =>
                    RemoveProperty(current, currentIndex, currentProperties[currentIndex], isFlow),
                onMatch: (currentIndex, updatedIndex, wireName) =>
                {
                    YamlTextNode? shapeValue =
                        shapeByName is not null
                        && shapeByName.TryGetValue(wireName, out var shapeProperty)
                            ? shapeProperty.Value
                            : null;
                    YamlTextNode? childShape = shapeValue;
                    ConfiglueModelSchema? childSchema = null;
                    if (_schemaShape is not null && currentSchema is not null)
                    {
                        _schemaShape.TryGetNested(currentSchema, wireName, out var nested);
                        childSchema = DocumentSemanticEditPlan.ResolveChildSchema(
                            currentSchema,
                            _schemaShape.RootSchema,
                            wireName,
                            nested,
                            shapeValue is null || shapeValue.Kind == YamlTextKind.Scalar,
                            shapeValue?.Kind == YamlTextKind.Mapping,
                            out var needsBareShape
                        );
                        if (needsBareShape && childSchema is not null)
                        {
                            childShape = _schemaShape.GetBareRootNode(childSchema);
                        }
                    }

                    AddDiff(
                        currentProperties[currentIndex].Value,
                        updatedProperties[updatedIndex].Value,
                        childShape,
                        currentProperties[currentIndex],
                        updatedProperties[updatedIndex],
                        childSchema
                    );
                },
                onAdd: (addUpdatedIndexes, retainedCurrentIndexes) =>
                {
                    if (addUpdatedIndexes.Length == 0)
                    {
                        return;
                    }

                    var retained = retainedCurrentIndexes
                        .Select(index => currentProperties[index])
                        .ToList();
                    var additions = addUpdatedIndexes
                        .Select(updatedIndex =>
                        {
                            var property = updatedProperties[updatedIndex];
                            return isFlow
                                ? Slice(
                                    property.Value.Source,
                                    property.KeyStart,
                                    property.Value.ValueEnd
                                )
                                : Slice(
                                    property.Value.Source,
                                    property.EntryStart,
                                    property.EntryEnd
                                );
                        })
                        .ToArray();
                    AddProperties(current, additions, retained);
                }
            );
        }

        private void AddSequenceDiff(
            YamlTextNode current,
            YamlTextNode updated,
            ConfiglueModelSchema? elementSchema = null
        )
        {
            var currentItems = current.Items!;
            var updatedItems = updated.Items!;
            var shared = Math.Min(currentItems.Count, updatedItems.Count);
            YamlTextNode? elementShape = null;
            if (elementSchema is not null && _schemaShape is not null)
            {
                elementShape = _schemaShape.GetBareRootNode(elementSchema);
            }

            for (var index = 0; index < shared; index++)
            {
                AddDiff(
                    currentItems[index],
                    updatedItems[index],
                    elementShape,
                    null,
                    null,
                    elementSchema
                );
            }

            if (updatedItems.Count < currentItems.Count)
            {
                for (var index = currentItems.Count - 1; index >= updatedItems.Count; index--)
                {
                    RemoveSequenceItem(current, index);
                }
            }
            else if (updatedItems.Count > currentItems.Count)
            {
                var isFlow = ((YamlSequence)current.Element).Style == YamlStyle.Flow;
                var additions = updatedItems
                    .Skip(currentItems.Count)
                    .Select(item =>
                        isFlow
                            ? Slice(updated.Source, item.Start, item.End)
                            : Slice(updated.Source, item.EntryStart, item.EntryEnd)
                    )
                    .ToArray();
                AddSequenceItems(current, additions);
            }
        }

        private void AddReplacement(
            YamlTextNode current,
            YamlTextNode updated,
            YamlTextProperty? currentProperty,
            YamlTextProperty? updatedProperty
        )
        {
            var start = currentProperty?.ValueStart ?? current.Start;
            var end = currentProperty?.ValueEnd ?? current.End;
            var updatedStart = updatedProperty?.ValueStart ?? updated.Start;
            var updatedEnd = updatedProperty?.ValueEnd ?? updated.End;
            var raw = Slice(updated.Source, updatedStart, updatedEnd);
            if (currentProperty is not null && updated.Kind != YamlTextKind.Scalar)
            {
                raw = Reindent(
                    raw,
                    GetIndentation(document.Source, currentProperty.EntryStart),
                    Newline
                );
            }

            _edits.Add(new TextEdit(start, end - start, raw));
        }

        private void RemoveProperty(
            YamlTextNode mapping,
            int index,
            YamlTextProperty property,
            bool isFlow
        )
        {
            if (isFlow)
            {
                var properties = mapping.Properties!;
                var start = property.KeyStart;
                var end = property.Value.End;
                var separatorStart = index > 0 ? properties[index - 1].Value.End : end;
                var separatorEnd =
                    index < properties.Count - 1 ? properties[index + 1].KeyStart : mapping.End - 1;
                var comma = -1;
                if (index < properties.Count - 1)
                {
                    comma = FindFlowComma(document.Source, end, separatorEnd);
                }
                else if (index > 0)
                {
                    comma = FindFlowComma(document.Source, separatorStart, start);
                }

                if (comma >= 0 && _removedFlowCommas.Add(comma))
                {
                    _edits.Add(new TextEdit(comma, 1, ""));
                }

                var flowComments = ExtractComments(document.Source, start, end);
                _edits.Add(new TextEdit(start, end - start, flowComments));
                return;
            }

            var comments = ExtractComments(document.Source, property.EntryStart, property.EntryEnd);
            _edits.Add(
                new TextEdit(property.EntryStart, property.EntryEnd - property.EntryStart, comments)
            );
        }

        private void RemoveSequenceItem(YamlTextNode sequence, int index)
        {
            var item = sequence.Items![index];
            if (((YamlSequence)sequence.Element).Style == YamlStyle.Flow)
            {
                var comma = -1;
                if (index < sequence.Items.Count - 1)
                {
                    comma = FindFlowComma(
                        document.Source,
                        item.End,
                        sequence.Items[index + 1].Start
                    );
                }
                else if (index > 0)
                {
                    comma = FindFlowComma(
                        document.Source,
                        sequence.Items[index - 1].End,
                        item.Start
                    );
                }

                if (comma >= 0 && _removedFlowCommas.Add(comma))
                {
                    _edits.Add(new TextEdit(comma, 1, ""));
                }

                var flowComments = ExtractComments(document.Source, item.Start, item.End);
                _edits.Add(new TextEdit(item.Start, item.End - item.Start, flowComments));
                return;
            }

            var comments = ExtractComments(document.Source, item.EntryStart, item.EntryEnd);
            _edits.Add(new TextEdit(item.EntryStart, item.EntryEnd - item.EntryStart, comments));
        }

        private void AddProperties(
            YamlTextNode mapping,
            IReadOnlyList<string> additions,
            IReadOnlyList<YamlTextProperty> retainedProperties
        )
        {
            if (mapping.Element is YamlMapping { Style: YamlStyle.Flow })
            {
                AddFlowEntries(
                    mapping,
                    additions,
                    false,
                    retainedProperties.Count,
                    retainedProperties.Count == 0 ? mapping.Start : retainedProperties[^1].Value.End
                );
                return;
            }

            string indentation;
            if (retainedProperties.Count == 0)
            {
                indentation = ReferenceEquals(mapping, document.Root)
                    ? ""
                    : GetIndentation(document.Source, mapping.Start) + "  ";
            }
            else
            {
                indentation = GetIndentation(document.Source, retainedProperties[0].EntryStart);
            }
            var content = additions
                .Select(addition => Reindent(addition, indentation, Newline))
                .ToArray();
            AddBlockEntries(mapping.End, content);
        }

        private void AddSequenceItems(YamlTextNode sequence, IReadOnlyList<string> additions)
        {
            if (sequence.Element is YamlSequence { Style: YamlStyle.Flow })
            {
                AddFlowEntries(
                    sequence,
                    additions,
                    true,
                    sequence.Items!.Count,
                    sequence.Items.Count == 0 ? sequence.Start : sequence.Items[^1].End
                );
                return;
            }

            var indentation =
                sequence.Items!.Count == 0
                    ? GetIndentation(document.Source, sequence.Start) + "  "
                    : GetIndentation(document.Source, sequence.Items[0].EntryStart);
            var content = additions
                .Select(addition => Reindent(addition, indentation, Newline))
                .ToArray();
            AddBlockEntries(sequence.End, content);
        }

        private void AddFlowEntries(
            YamlTextNode container,
            IReadOnlyList<string> additions,
            bool isSequence,
            int retainedCount,
            int lastEnd
        )
        {
            var close = container.End - 1;
            if (close < container.Start || document.Source[close] != (isSequence ? ']' : '}'))
            {
                throw new YamlException("The YAML flow collection has no closing delimiter.");
            }

            var hasSeparator =
                retainedCount > 0 && FindRetainedFlowComma(document.Source, lastEnd, close) >= 0;
            var prefix = !hasSeparator && retainedCount > 0 ? ", " : "";
            _edits.Add(
                new TextEdit(
                    close,
                    0,
                    prefix + string.Join(", ", additions.Select(static item => item.Trim()))
                )
            );
        }

        private int FindRetainedFlowComma(string source, int start, int end)
        {
            var position = start;
            while (position < end)
            {
                var comma = FindFlowComma(source, position, end);
                if (comma < 0)
                {
                    return -1;
                }

                if (!_removedFlowCommas.Contains(comma))
                {
                    return comma;
                }

                position = comma + 1;
            }

            return -1;
        }

        private static int FindFlowComma(string source, int start, int end)
        {
            var singleQuoted = false;
            var doubleQuoted = false;
            var depth = 0;
            var position = start;
            while (position < end)
            {
                var character = source[position];
                if (doubleQuoted)
                {
                    if (character == '\\')
                    {
                        position += 2;
                        continue;
                    }

                    if (character == '"')
                    {
                        doubleQuoted = false;
                    }
                }
                else if (singleQuoted)
                {
                    if (character == '\'' && position + 1 < end && source[position + 1] == '\'')
                    {
                        position += 2;
                        continue;
                    }

                    if (character == '\'')
                    {
                        singleQuoted = false;
                    }
                }
                else if (character == '"')
                {
                    if (YamlFlowScanning.IsQuoteStart(source, position))
                    {
                        doubleQuoted = true;
                    }
                }
                else if (character == '\'')
                {
                    if (YamlFlowScanning.IsQuoteStart(source, position))
                    {
                        singleQuoted = true;
                    }
                }
                else if (character == '#')
                {
                    if (!YamlFlowScanning.IsCommentStart(source, position))
                    {
                        position++;
                        continue;
                    }

                    while (position < end && source[position] is not '\r' and not '\n')
                    {
                        position++;
                    }

                    continue;
                }
                else if (character is '[' or '{')
                {
                    depth++;
                }
                else if (character is ']' or '}')
                {
                    depth--;
                }
                else if (character == ',' && depth == 0)
                {
                    return position;
                }

                position++;
            }

            return -1;
        }

        private void AddBlockEntries(int position, IReadOnlyList<string> entries)
        {
            var newline = FindNewline(document.Source);
            var prefix =
                position > 0 && document.Source[position - 1] is not '\r' and not '\n'
                    ? newline
                    : "";
            var content = string.Join(
                newline,
                entries.Select(static entry => entry.TrimEnd('\r', '\n'))
            );
            _edits.Add(new TextEdit(position, 0, prefix + content + newline));
        }

        private static bool Equivalent(YamlTextNode left, YamlTextNode right) =>
            left
                .Source.AsSpan(left.Start, left.End - left.Start)
                .SequenceEqual(right.Source.AsSpan(right.Start, right.End - right.Start));

        private static string Slice(string source, int start, int end) =>
            source[start..Math.Max(start, Math.Min(end, source.Length))];

        internal static string Reindent(string value, string indentation, string newline)
        {
            var normalized = value.Replace("\r\n", "\n").Replace('\r', '\n');
            var lines = normalized.Split('\n');
            var sourceIndent = lines
                .Where(static line => !string.IsNullOrWhiteSpace(line))
                .Select(static line =>
                    line.TakeWhile(static character => character is ' ' or '\t').Count()
                )
                .DefaultIfEmpty(0)
                .Min();
            return string.Join(
                newline,
                lines.Select(line =>
                {
                    if (line.Length == 0)
                    {
                        return line;
                    }

                    var remove = Math.Min(
                        sourceIndent,
                        line.TakeWhile(static character => character is ' ' or '\t').Count()
                    );
                    return indentation + line[remove..];
                })
            );
        }

        private static string ExtractComments(string source, int start, int end)
        {
            var result = new StringBuilder();
            var position = start;
            while (position < end)
            {
                var lineEnd = position;
                while (lineEnd < end && source[lineEnd] is not '\r' and not '\n')
                {
                    lineEnd++;
                }

                var line = source.AsSpan(position, lineEnd - position);
                var comment = FindCommentStart(line);
                if (comment >= 0)
                {
                    var indentation = 0;
                    while (indentation < comment && line[indentation] is ' ' or '\t')
                    {
                        indentation++;
                    }

                    result.Append(line[..indentation].ToString());
                    result.Append(line[comment..].ToString());
                    result.Append(FindNewline(source));
                }

                position = lineEnd;
                if (position < end && source[position] == '\r')
                {
                    position++;
                }

                if (position < end && source[position] == '\n')
                {
                    position++;
                }
            }

            return result.ToString();
        }

        private static int FindCommentStart(ReadOnlySpan<char> line)
        {
            var singleQuoted = false;
            var doubleQuoted = false;
            var index = 0;
            while (index < line.Length)
            {
                var character = line[index];
                if (doubleQuoted)
                {
                    if (character == '\\')
                    {
                        index += 2;
                        continue;
                    }

                    if (character == '"')
                    {
                        doubleQuoted = false;
                    }
                }
                else if (singleQuoted)
                {
                    if (character == '\'' && index + 1 < line.Length && line[index + 1] == '\'')
                    {
                        index += 2;
                        continue;
                    }

                    if (character == '\'')
                    {
                        singleQuoted = false;
                    }
                }
                else if (character == '"' && YamlFlowScanning.IsQuoteStart(line, index))
                {
                    doubleQuoted = true;
                }
                else if (character == '\'' && YamlFlowScanning.IsQuoteStart(line, index))
                {
                    singleQuoted = true;
                }
                else if (character == '#' && YamlFlowScanning.IsCommentStart(line, index))
                {
                    return index;
                }

                index++;
            }

            return -1;
        }

        private static int FindLineStart(string source, int position)
        {
            while (position > 0 && source[position - 1] is not '\r' and not '\n')
            {
                position--;
            }

            return position;
        }

        private static string GetIndentation(string source, int position)
        {
            var lineStart = FindLineStart(source, position);
            var length = 0;
            while (lineStart + length < source.Length && source[lineStart + length] is ' ' or '\t')
            {
                length++;
            }

            return source.Substring(lineStart, length);
        }
    }

    private sealed class TextEdit(int start, int length, string content)
    {
        internal int Start { get; } = start;

        internal int Length { get; } = length;

        internal string Content { get; } = content;
    }
}

internal sealed class YamlSchemaShape
{
    private readonly JsonNamingPolicy? _namingPolicy;
    private readonly YamlSerializerOptions? _serializerOptions;
    private readonly System.Collections.Concurrent.ConcurrentDictionary<
        string,
        BareLevel
    > _bareCache = new(StringComparer.Ordinal);

    private YamlSchemaShape(
        ConfiglueModelSchema rootSchema,
        byte[] rootShapeBytes,
        YamlTextNode rootNode,
        JsonNamingPolicy? namingPolicy,
        YamlSerializerOptions? serializerOptions
    )
    {
        RootSchema = rootSchema;
        RootShapeBytes = rootShapeBytes;
        RootNode = rootNode;
        _namingPolicy = namingPolicy;
        _serializerOptions = serializerOptions;
    }

    internal ConfiglueModelSchema RootSchema { get; }

    internal byte[] RootShapeBytes { get; }

    internal YamlTextNode RootNode { get; }

    internal static YamlSchemaShape Create(
        ConfiglueModelSchema schema,
        JsonNamingPolicy? namingPolicy,
        YamlSerializerOptions? serializerOptions,
        DocumentLayoutOptions? layout,
        Encoding? textEncoding = null
    )
    {
        var rootBytes = YamlDocumentEditor.CreateSchemaShape(
            schema,
            namingPolicy,
            serializerOptions,
            layout,
            textEncoding
        );
        var decoded = DecodeBytes(rootBytes, textEncoding);
        var rootNode = YamlTextDocument.Parse(decoded).Root;
        var effectiveNaming = namingPolicy ?? serializerOptions?.PropertyNamingPolicy;
        return new YamlSchemaShape(schema, rootBytes, rootNode, effectiveNaming, serializerOptions);
    }

    internal bool TryGetNested(
        ConfiglueModelSchema parent,
        string wireName,
        out ConfiglueModelSchema? nested
    )
    {
        nested = null;
        foreach (var member in parent.Members)
        {
            if (member.NestedSchemaFactory is null)
            {
                continue;
            }

            var wire = _namingPolicy?.ConvertName(member.Name) ?? member.Name;
            if (string.Equals(wire, wireName, StringComparison.Ordinal))
            {
                try
                {
                    nested = member.NestedSchemaFactory();
                }
                catch (Exception exception) when (exception is not StackOverflowException)
                {
                    throw new InvalidOperationException(
                        $"Failed to resolve nested schema for member '{member.Name}' in schema '{parent.Id}'.",
                        exception
                    );
                }

                return true;
            }
        }

        return false;
    }

    internal YamlTextNode GetBareRootNode(ConfiglueModelSchema schema) => GetBareLevel(schema).Root;

    private BareLevel GetBareLevel(ConfiglueModelSchema schema) =>
        _bareCache.GetOrAdd(
            DocumentSemanticEditPlan.CacheKey(schema),
            static (_, state) =>
                CreateBareLevel(state.Naming, state.SerializerOptions, state.Schema),
            (Naming: _namingPolicy, SerializerOptions: _serializerOptions, Schema: schema)
        );

    private static BareLevel CreateBareLevel(
        JsonNamingPolicy? namingPolicy,
        YamlSerializerOptions? serializerOptions,
        ConfiglueModelSchema schema
    )
    {
        var fragment = DocumentSemanticEditPlan.CreateShallowPresentFragment(schema);
        var yamlValue = FragmentYamlConverterFactory.ToYamlValue(fragment, schema, namingPolicy);
        var options = serializerOptions ?? YamlSerializerOptions.Default;
        var text = YamlSerializer.Serialize(yamlValue, yamlValue.GetType(), options);
        var document = YamlTextDocument.Parse(text);
        if (document.Root.Kind != YamlTextKind.Mapping)
        {
            throw new YamlException("The generated YAML bare shape must be a mapping.");
        }

        return new BareLevel(document.Root);
    }

    private static string DecodeBytes(byte[] bytes, Encoding? textEncoding)
    {
        if (textEncoding is null)
        {
            return new UTF8Encoding(false, true).GetString(bytes);
        }

        using var stream = new MemoryStream(bytes, writable: false);
        using var reader = new StreamReader(
            stream,
            textEncoding,
            detectEncodingFromByteOrderMarks: true
        );
        var text = reader.ReadToEnd();
        return text.Length > 0 && text[0] == '\uFEFF' ? text.Substring(1) : text;
    }

    private sealed class BareLevel(YamlTextNode root)
    {
        public YamlTextNode Root { get; } = root;
    }
}
