<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="bunit" Version="2.11.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/basic/Configlue.Abstraction/Configlue.Abstraction.csproj" />
    <ProjectReference Include="../../src/basic/Configlue.Core/Configlue.Core.csproj" />
    <ProjectReference Include="../../src/basic/Configlue.Testing/Configlue.Testing.csproj" />
    <ProjectReference Include="../../src/devtools/Configlue.DevTools/Configlue.DevTools.csproj" />
    <ProjectReference Include="../../src/devtools/Configlue.DevTools.Web/Configlue.DevTools.Web.csproj" />
    <ProjectReference Include="../../src/extensions/Configlue.Extensions.DI/Configlue.Extensions.DI.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.AspNetCore/Configlue.Hosting.AspNetCore.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.Blazor/Configlue.Hosting.Blazor.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.Avalonia/Configlue.Hosting.Avalonia.csproj" />
    <ProjectReference Include="../../src/hosting/Configlue.Hosting.Godot/Configlue.Hosting.Godot.csproj" />
    <ProjectReference
      Include="../../src/tools/Configlue.Generator/Configlue.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>
</Project>
