<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Configlue.Source.Common</AssemblyName>
    <RootNamespace>Configlue.Source.Common</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageDescription>Common layered source presets for Configlue.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Configlue.Core/Configlue.Core.csproj" />
    <ProjectReference Include="../Configlue.Provider.Json/Configlue.Provider.Json.csproj" />
    <ProjectReference Include="../Configlue.Source.Environment/Configlue.Source.Environment.csproj" />
  </ItemGroup>
</Project>
