<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>SparseFragments.Generator</AssemblyName>
    <RootNamespace>SparseFragments.Generator</RootNamespace>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsPackable>false</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PackageDescription>Standalone source generator for SparseFragments models.</PackageDescription>
    <NoWarn>$(NoWarn);RS2008;NU5128</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Polyfill" Version="11.4.1" />
    <PackageReference
      Include="Microsoft.CodeAnalysis.CSharp"
      Version="4.11.0"
      PrivateAssets="all"
    />
    <PackageReference
      Include="Microsoft.CodeAnalysis.Analyzers"
      Version="3.11.0"
      PrivateAssets="all"
    />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SparseFragments.Generator.Shared\**\*.cs" LinkBase="Shared" />
  </ItemGroup>
</Project>
