using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace SparseFragments.Generator.Shared;

/// <summary>Builds standalone generated source for a <c>[SparseFragmentModel]</c>.</summary>
internal static class SparseFragmentEmitter
{
    private const string Runtime = SparseWellKnownNames.RuntimeNamespace;
    private const string Optional = SparseWellKnownNames.OptionalType;
    private const string FragmentMember = SparseWellKnownNames.FragmentMemberType;
    private const string FragmentInterface = SparseWellKnownNames.FragmentInterfaceType;
    private const string FragmentOfT = SparseWellKnownNames.FragmentInterfaceType;
    private const string DeepCloneable = SparseWellKnownNames.DeepCloneableType;
    private const string Schema = SparseWellKnownNames.SchemaType;
    private const string MemberSchema = SparseWellKnownNames.MemberSchemaType;
    private const string MergeStrategy = SparseWellKnownNames.MergeStrategyType;
    private const string ValueComparer = SparseWellKnownNames.ValueComparerType;
    private const string ReferenceComparer = SparseWellKnownNames.ReferenceComparerType;
    private const string CollectionMerger = SparseWellKnownNames.CollectionMergerType;

    public static string BuildSource(
        SparseModelInfo model,
        ImmutableArray<SparseMemberModel> members,
        ImmutableArray<SparsePocoCloneModel> pocoCloneModels,
        ImmutableArray<SparseStructuralModel> structuralModels,
        CancellationToken cancellationToken
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        var modelType = model.ModelTypeName;
        var generatedType = ModelDeclarationKeyword(model);
        var name = SparseNaming.EscapeIdentifier(model.Name);
        var code = new SharedIndentedBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        if (!model.IsGlobalNamespace)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";");
        }

        code.Append(generatedType)
            .Append(name)
            .Append(" : ")
            .Append(DeepCloneable)
            .Append("<")
            .Append(modelType)
            .AppendLine(">");
        code.AppendLine("{");
        AppendDeepClone(code, modelType, members, !pocoCloneModels.IsEmpty);
        AppendPocoCloneHelpers(code, pocoCloneModels);
        AppendCollectionCloneHelpers(code);
        AppendFragment(code, modelType, members, !model.IsStruct, !pocoCloneModels.IsEmpty);
        AppendStructuralModels(code, structuralModels, !pocoCloneModels.IsEmpty);
        code.AppendLine("}");
        return code.ToString();
    }

    private static string ModelDeclarationKeyword(SparseModelInfo model)
    {
        if (model.IsStruct)
        {
            return model.IsRecord ? "partial record struct " : "partial struct ";
        }

        return model.IsRecord ? "partial record class " : "partial class ";
    }

    private static void AppendStructuralModels(
        SharedIndentedBuilder code,
        ImmutableArray<SparseStructuralModel> structuralModels,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var structuralModel in structuralModels)
        {
            code.AppendLineAt(
                1,
                "/// <summary>Generated shape for an undecorated structural member type.</summary>"
            );
            code.AppendLineAt(1, "public sealed partial class " + structuralModel.HostName);
            code.AppendLineAt(1, "{");
            code.IndentOffset++;
            AppendFragment(
                code,
                structuralModel.ValueTypeName,
                structuralModel.Members,
                true,
                usesPocoCloning
            );
            code.IndentOffset--;
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendCollectionCloneHelpers(SharedIndentedBuilder code)
    {
        code.AppendLineAt(
            1,
            "private static global::System.Collections.Concurrent.BlockingCollection<T> __CloneBlockingCollection<T>(global::System.Collections.Concurrent.BlockingCollection<T> original, global::System.Collections.Generic.IEnumerable<T> items)"
        );
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "var queue = new global::System.Collections.Concurrent.ConcurrentQueue<T>(items);"
        );
        code.AppendLineAt(2, "var clone = original.BoundedCapacity > 0");
        code.AppendLineAt(
            3,
            "? new global::System.Collections.Concurrent.BlockingCollection<T>(queue, original.BoundedCapacity)"
        );
        code.AppendLineAt(
            3,
            ": new global::System.Collections.Concurrent.BlockingCollection<T>(queue);"
        );
        code.AppendLineAt(2, "if (original.IsAddingCompleted)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "clone.CompleteAdding();");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(2, "return clone;");
        code.AppendLineAt(1, "}");
    }

    private static void AppendDeepClone(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendIndent(1).Append("public ").Append(modelType).AppendLine(" DeepClone()");
        code.AppendLineAt(1, "{");
        if (usesPocoCloning)
        {
            AppendCloneContext(code, 2);
        }

        code.AppendIndent(2).Append("return new ").Append(modelType).AppendLine();
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            code.AppendIndent(2)
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .Append(" = ")
                .Append(
                    CloneModelExpression(
                        member,
                        "this." + SparseNaming.EscapeIdentifier(member.Property.Name)
                    )
                )
                .AppendLine(",");
        }

        code.AppendLineAt(1, "};");
        code.AppendLineAt(1, "}");
    }

    private static void AppendPocoCloneHelpers(
        SharedIndentedBuilder code,
        ImmutableArray<SparsePocoCloneModel> pocoTypes
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        foreach (var pocoType in pocoTypes)
        {
            var typeName = pocoType.Model.ModelTypeName;
            code.AppendIndent(1)
                .Append("private static ")
                .Append(typeName)
                .Append(' ')
                .Append(pocoType.CloneHelperName)
                .Append('(')
                .Append(typeName)
                .AppendLine(
                    " value, global::System.Collections.Generic.Dictionary<object, object> __sparse_clone_context)"
                );
            code.AppendLineAt(1, "{");
            code.AppendLineAt(
                2,
                "if (__sparse_clone_context.TryGetValue(value, out var existing)) { return ("
                    + typeName
                    + ")existing; }"
            );
            code.AppendIndent(2).Append("var clone = new ").Append(typeName).AppendLine("();");
            code.AppendLineAt(2, "__sparse_clone_context.Add(value, clone);");
            foreach (var member in pocoType.Members)
            {
                var memberName = SparseNaming.EscapeIdentifier(member.Property.Name);
                code.AppendIndent(2)
                    .Append("clone.")
                    .Append(memberName)
                    .Append(" = ")
                    .Append(CloneModelExpression(member, "value." + memberName))
                    .AppendLine(";");
            }

            code.AppendLineAt(2, "return clone;");
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendCloneContext(SharedIndentedBuilder code, int indent)
    {
        code.AppendIndent(indent)
            .Append(
                "var __sparse_clone_context = new global::System.Collections.Generic.Dictionary<object, object>("
            )
            .Append(ReferenceComparer)
            .AppendLine(".Instance);");
    }

    private static void AppendFragment(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool modelIsReferenceType,
        bool usesPocoCloning
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendLineAt(
            1,
            "/// <summary>A sparse, presence-aware representation of this model.</summary>"
        );
        code.AppendLineAt(
            1,
            "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
        );
        code.AppendIndent(1)
            .Append("public sealed partial class Fragment : ")
            .Append(FragmentOfT)
            .Append("<Fragment>, ")
            .Append(DeepCloneable)
            .AppendLine("<Fragment>");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            code.AppendIndent(2)
                .Append("public ")
                .Append(Optional)
                .Append("<")
                .Append(FragmentValueType(member))
                .Append("> ")
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .AppendLine(" { get; init; }");
        }

        foreach (var member in members.Where(static member => member.MergeStrategyType is not null))
        {
            code.AppendIndent(2)
                .Append("internal static readonly ")
                .Append(member.MergeStrategyType!.Value.Name)
                .Append(" ")
                .Append(MergeStrategyField(member))
                .Append(" = new ")
                .Append(member.MergeStrategyType.Value.Name)
                .AppendLine("();");
        }

        code.AppendLine();
        code.AppendLineAt(2, "/// <summary>Whether this fragment has no present members.</summary>");
        code.AppendIndent(2)
            .Append("public bool IsEmpty => ")
            .Append(
                members.Length == 0
                    ? "true"
                    : string.Join(
                        " && ",
                        members.Select(member =>
                            "!" + SparseNaming.EscapeIdentifier(member.Property.Name) + ".IsPresent"
                        )
                    )
            )
            .AppendLine(";");
        code.AppendLine();
        AppendFragmentDescriptor(code, modelType, members);
        AppendFromModel(code, modelType, members, modelIsReferenceType, usesPocoCloning);
        AppendToModel(code, modelType, members);
        AppendMerge(code, members);
        AppendApplyChanges(code, members);
        AppendDiff(code, modelType, members, modelIsReferenceType);
        AppendFragmentClone(code, members, usesPocoCloning);
        code.AppendLineAt(1, "}");
    }

    private static void AppendFragmentDescriptor(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.CancellationToken.ThrowIfCancellationRequested();
        code.AppendLineAt(2, "/// <summary>The empty fragment.</summary>");
        code.AppendLineAt(2, "public static Fragment Empty { get; } = new();");
        code.AppendIndent(2)
            .Append("public static ")
            .Append(Schema)
            .Append(" FragmentSchema { get; } = new(typeof(")
            .Append(modelType)
            .AppendLine("), new " + MemberSchema + "[]");
        code.AppendLineAt(2, "{");
        foreach (var member in members)
        {
            var valueType = member.ChildModel is null
                ? member.Property.Type.NonNullableName
                : member.ChildFragmentType!;
            code.AppendIndent(3)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append(valueType)
                .Append("), ")
                .Append(Runtime)
                .Append(".MergeMode.")
                .Append(SparseNaming.MergeModeName(member.MergeMode))
                .Append(", static value => ((")
                .Append(modelType)
                .Append(")value).")
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .Append(", ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(member.ChildFragmentType!)
                    .Append(".FragmentSchema");
            }

            code.Append(", ")
                .Append(
                    member.MergeStrategyType is null ? "null" : MergeStrategyField(member)
                )
                .Append(", static () => default(")
                .Append(member.Property.Type.Name)
                .AppendLine(")),");
        }

        code.AppendIndent(2).Append("}, static () => Fragment.Empty);");
        code.AppendIndent(2).Append("public ").Append(Schema).AppendLine(" Schema => FragmentSchema;");
        code.AppendLineAt(
            2,
            "public global::System.Collections.Generic.IEnumerable<" + FragmentMember + "> EnumeratePresentMembers()"
        );
        code.AppendLineAt(2, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(3)
                .Append("if (")
                .Append(name)
                .Append(".IsPresent) yield return new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", ")
                .Append(name)
                .AppendLine(".Value);");
        }

        code.AppendLineAt(2, "}");
        AppendWithMember(code, members);
        AppendWithoutMember(code, members);
        code.AppendLine();
    }

    private static void AppendWithMember(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendIndent(2)
            .Append("public ")
            .Append(FragmentInterface)
            .AppendLine(" WithMember(int memberId, object? value)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "switch (memberId)");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(4).Append("case ").Append(member.Id).AppendLine(":");
            code.AppendIndent(5).Append("return new Fragment");
            code.AppendLine();
            code.AppendLineAt(5, "{");
            foreach (var copy in members)
            {
                var copyName = SparseNaming.EscapeIdentifier(copy.Property.Name);
                code.AppendIndent(6)
                    .Append(copyName)
                    .Append(" = ")
                    .Append(copyName == name
                        ? Optional + "<" + FragmentValueType(copy) + ">.Present((" + FragmentValueType(copy) + ")value!)"
                        : "this." + copyName)
                    .AppendLine(",");
            }

            code.AppendLineAt(5, "};");
        }

        code.AppendLineAt(
            4,
            "default: throw new global::System.ArgumentOutOfRangeException(nameof(memberId));"
        );
        code.AppendLineAt(3, "}");
        code.AppendLineAt(2, "}");
    }

    private static void AppendWithoutMember(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendIndent(2)
            .Append("public ")
            .Append(FragmentInterface)
            .AppendLine(" WithoutMember(int memberId)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "switch (memberId)");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(4).Append("case ").Append(member.Id).AppendLine(":");
            code.AppendIndent(5).Append("return new Fragment");
            code.AppendLine();
            code.AppendLineAt(5, "{");
            foreach (var copy in members)
            {
                var copyName = SparseNaming.EscapeIdentifier(copy.Property.Name);
                code.AppendIndent(6)
                    .Append(copyName)
                    .Append(" = ")
                    .Append(copyName == name ? "default" : "this." + copyName)
                    .AppendLine(",");
            }

            code.AppendLineAt(5, "};");
        }

        code.AppendLineAt(
            4,
            "default: throw new global::System.ArgumentOutOfRangeException(nameof(memberId));"
        );
        code.AppendLineAt(3, "}");
        code.AppendLineAt(2, "}");
    }

    private static void AppendFromModel(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool modelIsReferenceType,
        bool usesPocoCloning
    )
    {
        code.AppendIndent(2)
            .Append("public static Fragment From(")
            .Append(modelType)
            .AppendLine(" value)");
        code.AppendLineAt(2, "{");
        if (modelIsReferenceType)
        {
            AppendNullGuard(code, 3, "value");
        }

        if (usesPocoCloning)
        {
            AppendCloneContext(code, 3);
        }

        code.AppendLineAt(3, "return new Fragment");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var access = "value." + SparseNaming.EscapeIdentifier(member.Property.Name);
            string value;
            if (member.ChildModel is null)
            {
                value = CloneModelExpression(member, access);
            }
            else if (!member.ChildIsReferenceType)
            {
                value = $"{member.ChildFragmentType}.From({access})";
            }
            else
            {
                value = $"({access} is null ? null : {member.ChildFragmentType}.From({access}))";
            }

            code.AppendIndent(4)
                .Append(SparseNaming.EscapeIdentifier(member.Property.Name))
                .Append(" = ")
                .Append(Optional)
                .Append("<")
                .Append(FragmentValueType(member))
                .Append(">.Present(")
                .Append(value)
                .AppendLine("),");
        }

        code.AppendLineAt(3, "};");
        code.AppendLineAt(2, "}");
        code.AppendLine();
    }

    private static void AppendToModel(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendIndent(2).Append("public ").Append(modelType).AppendLine(" ToModel()");
        code.AppendLineAt(2, "{");
        if (!members.IsEmpty)
        {
            code.AppendIndent(3).Append("if (");
            for (var index = 0; index < members.Length; index++)
            {
                if (index > 0)
                {
                    code.Append(" && ");
                }

                code.Append(SparseNaming.EscapeIdentifier(members[index].Property.Name))
                    .Append(".IsPresent");
            }

            code.AppendLine(")");
            code.AppendLineAt(3, "{");
            AppendModelInitializer(code, modelType, members, 4, false);
            code.AppendLineAt(3, "}");
        }

        code.AppendIndent(3).Append("var defaults = new ").Append(modelType).AppendLine("();");
        AppendModelInitializer(code, modelType, members, 3, true);
        code.AppendLineAt(2, "}");
        code.AppendLine();
    }

    private static void AppendModelInitializer(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        int indent,
        bool useDefaults
    )
    {
        code.AppendIndent(indent).Append("return new ").Append(modelType).AppendLine();
        code.AppendLineAt(indent, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            string value;
            if (member.ChildModel is null)
            {
                value = name + ".Value!";
            }
            else if (!member.ChildIsReferenceType)
            {
                value = name + ".Value!.ToModel()";
            }
            else
            {
                value = name + ".Value?.ToModel()!";
            }

            code.AppendIndent(indent + 1)
                .Append(name)
                .Append(" = ")
                .Append(useDefaults ? name + ".IsPresent ? " + value + " : defaults." + name : value)
                .AppendLine(",");
        }

        code.AppendLineAt(indent, "};");
    }

    private static void AppendMerge(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        var hasCustomMergeStrategy = false;
        var replaceOnly = members.Length > 0;
        foreach (var member in members)
        {
            if (member.MergeStrategyType is not null)
            {
                hasCustomMergeStrategy = true;
                replaceOnly = false;
                continue;
            }

            if ((member.MergeMode == 1 && member.ChildModel is not null) || member.MergeMode is 2 or 3)
            {
                replaceOnly = false;
            }
        }

        code.AppendLineAt(2, "/// <summary>Merges a higher-priority fragment over this fragment.</summary>");
        code.AppendLineAt(2, "public Fragment Merge(Fragment higherPriority)");
        code.AppendLineAt(2, "{");
        AppendNullGuard(code, 3, "higherPriority");
        if (!hasCustomMergeStrategy)
        {
            code.AppendLineAt(3, "if (higherPriority.IsEmpty)");
            code.AppendLineAt(3, "{");
            code.AppendLineAt(4, "return this;");
            code.AppendLineAt(3, "}");
            code.AppendLineAt(3, "if (IsEmpty)");
            code.AppendLineAt(3, "{");
            code.AppendLineAt(4, "return higherPriority;");
            code.AppendLineAt(3, "}");
        }

        if (replaceOnly)
        {
            code.AppendIndent(3).Append("if (");
            for (var index = 0; index < members.Length; index++)
            {
                if (index > 0)
                {
                    code.Append(" && ");
                }

                code.Append("higherPriority.")
                    .Append(SparseNaming.EscapeIdentifier(members[index].Property.Name))
                    .Append(".IsPresent");
            }

            code.AppendLine(")");
            code.AppendLineAt(3, "{");
            code.AppendLineAt(4, "return higherPriority;");
            code.AppendLineAt(3, "}");
        }

        code.AppendLineAt(3, "return new Fragment");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            var lower = "this." + name;
            var higher = "higherPriority." + name;
            string expression;
            if (member.MergeStrategyType is not null)
            {
                expression = $"{MergeStrategyField(member)}.Merge({lower}, {higher})";
            }
            else if (member.MergeMode == 1 && member.ChildModel is not null)
            {
                expression =
                    $"{higher}.IsPresent ? {Optional}<{FragmentValueType(member)}>.Present(({lower}.IsPresent && (object?){lower}.Value is not null && (object?){higher}.Value is not null) ? {lower}.Value!.Merge({higher}.Value!) : {higher}.Value) : {lower}";
            }
            else if (member.MergeMode is 2 or 3)
            {
                var merged = BuildCollectionMerge(member, lower + ".Value!", higher + ".Value!");
                expression =
                    $"{higher}.IsPresent ? ({lower}.IsPresent && (object?){lower}.Value is not null && (object?){higher}.Value is not null ? {Optional}<{FragmentValueType(member)}>.Present({merged}) : {higher}) : {lower}";
            }
            else
            {
                expression = $"{higher}.IsPresent ? {higher} : {lower}";
            }

            code.AppendIndent(4).Append(name).Append(" = ").Append(expression).AppendLine(",");
        }

        code.AppendLineAt(3, "};");
        code.AppendLineAt(2, "}");
        code.AppendLine();
    }

    private static void AppendApplyChanges(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members
    )
    {
        code.AppendLineAt(2, "/// <summary>Applies a sparse semantic diff to this contribution.</summary>");
        code.AppendLineAt(2, "public Fragment ApplyChanges(Fragment changes)");
        code.AppendLineAt(2, "{");
        AppendNullGuard(code, 3, "changes");
        code.AppendLineAt(3, "return new Fragment");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            var type = FragmentValueType(member);
            var expression = member.ChildModel is null
                ? $"changes.{name}.IsPresent ? changes.{name} : this.{name}"
                : $"changes.{name}.IsPresent ? {Optional}<{type}>.Present((this.{name}.IsPresent && (object?)this.{name}.Value is not null && (object?)changes.{name}.Value is not null) ? this.{name}.Value!.ApplyChanges(changes.{name}.Value!) : changes.{name}.Value) : this.{name}";
            code.AppendIndent(4).Append(name).Append(" = ").Append(expression).AppendLine(",");
        }

        code.AppendLineAt(3, "};");
        code.AppendLineAt(2, "}");
        code.AppendLine();
    }

    private static void AppendDiff(
        SharedIndentedBuilder code,
        string modelType,
        ImmutableArray<SparseMemberModel> members,
        bool modelIsReferenceType
    )
    {
        foreach (var member in members.Where(static member => member.ChildModel is not null))
        {
            var type = member.ChildModel!.Value.NonNullableName;
            var fragment = member.ChildFragmentType!;
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            code.AppendIndent(2)
                .Append("private static ")
                .Append(Optional)
                .Append("<")
                .Append(FragmentValueType(member))
                .Append("> __Diff_")
                .Append(name)
                .Append('(');
            if (!member.ChildIsReferenceType)
            {
                code.Append(type).Append(" before, ").Append(type).AppendLine(" after)");
                code.AppendLineAt(2, "{");
                code.AppendIndent(3)
                    .Append("if (global::System.Collections.Generic.EqualityComparer<")
                    .Append(type)
                    .AppendLine(">.Default.Equals(before, after)) { return default; }");
                code.AppendIndent(3)
                    .Append("return ")
                    .Append(Optional)
                    .Append("<")
                    .Append(FragmentValueType(member))
                    .Append(">.Present(")
                    .Append(fragment)
                    .AppendLine(".Diff(before, after));");
                code.AppendLineAt(2, "}");
                continue;
            }

            code.Append(type).Append("? before, ").Append(type).AppendLine("? after)");
            code.AppendLineAt(2, "{");
            code.AppendLineAt(3, "if (global::System.Object.ReferenceEquals(before, after)) { return default; }");
            code.AppendIndent(3)
                .Append("if (before is null || after is null) { return ")
                .Append(Optional)
                .Append("<")
                .Append(FragmentValueType(member))
                .Append(">.Present(after is null ? null : ")
                .Append(fragment)
                .AppendLine(".From(after)); }");
            code.AppendIndent(3)
                .Append("var difference = ")
                .Append(fragment)
                .AppendLine(".Diff(before, after);");
            code.AppendIndent(3)
                .Append("return difference.IsEmpty ? default : ")
                .Append(Optional)
                .Append("<")
                .Append(FragmentValueType(member))
                .AppendLine(">.Present(difference);");
            code.AppendLineAt(2, "}");
        }

        code.AppendLineAt(2, "/// <summary>Creates a sparse semantic diff between two ordinary model values.</summary>");
        code.AppendIndent(2)
            .Append("public static Fragment Diff(")
            .Append(modelType)
            .Append(" before, ")
            .Append(modelType)
            .AppendLine(" after)");
        code.AppendLineAt(2, "{");
        if (modelIsReferenceType)
        {
            AppendNullGuard(code, 3, "before");
            AppendNullGuard(code, 3, "after");
        }

        code.AppendLineAt(3, "return new Fragment");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            var before = "before." + name;
            var after = "after." + name;
            var valueType = FragmentValueType(member);
            string condition;
            if (member.MergeStrategyType is not null)
            {
                condition =
                    $"{MergeStrategyField(member)}.AreEqual({before}, {after}) ? default : {Optional}<{valueType}>.Present({after})";
            }
            else if (member.ChildModel is null)
            {
                condition =
                    $"{ValueEqualityExpression(member, before, after)} ? default : {Optional}<{valueType}>.Present({after})";
            }
            else
            {
                condition = $"__Diff_{name}({before}, {after})";
            }

            code.AppendIndent(4).Append(name).Append(" = ").Append(condition).AppendLine(",");
        }

        code.AppendLineAt(3, "};");
        code.AppendLineAt(2, "}");
        code.AppendLine();
    }

    private static void AppendFragmentClone(
        SharedIndentedBuilder code,
        ImmutableArray<SparseMemberModel> members,
        bool usesPocoCloning
    )
    {
        code.AppendLineAt(2, "/// <summary>Copies the fragment and its generated nested values.</summary>");
        code.AppendLineAt(2, "public Fragment DeepClone()");
        code.AppendLineAt(2, "{");
        if (usesPocoCloning)
        {
            AppendCloneContext(code, 3);
        }

        code.AppendLineAt(3, "return new Fragment");
        code.AppendLineAt(3, "{");
        foreach (var member in members)
        {
            var name = SparseNaming.EscapeIdentifier(member.Property.Name);
            var type = FragmentValueType(member);
            var expression = CloneFragmentExpression(member, "this." + name + ".Value");
            code.AppendIndent(4)
                .Append(name)
                .Append(" = this.")
                .Append(name)
                .Append(".IsPresent ? ")
                .Append(Optional)
                .Append("<")
                .Append(type)
                .Append(">.Present(")
                .Append(expression)
                .AppendLine(" ) : default,");
        }

        code.AppendLineAt(3, "};");
        code.AppendLineAt(2, "}");
        code.AppendLine();
    }

    private static void AppendNullGuard(SharedIndentedBuilder code, int indent, string variable)
    {
        code.AppendLineAt(indent, "if (" + variable + " is null)");
        code.AppendLineAt(indent, "{");
        code.AppendLineAt(
            indent + 1,
            "throw new global::System.ArgumentNullException(nameof(" + variable + "));"
        );
        code.AppendLineAt(indent, "}");
    }

    private static string FragmentValueType(SparseMemberModel member) =>
        member.ChildModel is null ? member.Property.Type.Name : member.ChildFragmentType + "?";

    private static string MergeStrategyField(SparseMemberModel member) =>
        SparseWellKnownNames.MergeStrategyFieldPrefix + member.Id;

    private static string ValueEqualityExpression(
        SparseMemberModel member,
        string left,
        string right
    )
    {
        var collection = member.Collection;
        return collection.CloneKind switch
        {
            SparseCloneCollectionKind.Set
            or SparseCloneCollectionKind.SortedSet
            or SparseCloneCollectionKind.ImmutableSet =>
                $"{ValueComparer}.AreSetEqual<{collection.ElementType.Name}>({left}, {right})",
            SparseCloneCollectionKind.Dictionary
            or SparseCloneCollectionKind.ImmutableDictionary when collection.ValueType is not null =>
                $"{ValueComparer}.AreDictionaryEqual<{collection.ElementType.Name}, {collection.ValueType.Value.Name}>({left}, {right})",
            _ => $"{ValueComparer}.AreEqual({left}, {right})",
        };
    }

    private static string CloneValueExpression(SparseTypeModel type, string access)
    {
        if (type.IsFragmentModel)
        {
            return type.IsReferenceType
                ? $"{access} is null ? default! : (({type.Name}){access}).DeepClone()"
                : $"(({type.Name}){access}).DeepClone()";
        }

        var cloneHelperName = type.PocoCloneHelperName;
        if (cloneHelperName is not null)
        {
            return type.IsReferenceType
                ? $"{access} is null ? default! : {cloneHelperName}({access}, __sparse_clone_context)"
                : $"{cloneHelperName}({access}, __sparse_clone_context)";
        }

        return access;
    }

    private static string CloneModelExpression(SparseMemberModel member, string access)
    {
        if (member.ChildModel is not null && !member.ChildIsStructural)
        {
            return member.ChildIsReferenceType
                ? $"{access} is null ? null! : {access}.DeepClone()"
                : $"(({member.Property.Type.Name}){access}).DeepClone()";
        }

        var cloneHelperName = member.Property.Type.PocoCloneHelperName;
        if (cloneHelperName is not null)
        {
            return member.Property.Type.IsReferenceType
                ? $"{access} is null ? null! : {cloneHelperName}({access}, __sparse_clone_context)"
                : $"{cloneHelperName}({access}, __sparse_clone_context)";
        }

        var cloned = CloneCollectionExpression(member, access);
        return member.Property.Type.IsReferenceType
            ? $"{access} is null ? null! : {cloned}"
            : cloned;
    }

    private static string CloneFragmentExpression(SparseMemberModel member, string access)
    {
        if (member.ChildModel is not null)
        {
            return $"{access}?.DeepClone()";
        }

        var cloneHelperName = member.Property.Type.PocoCloneHelperName;
        if (cloneHelperName is not null)
        {
            return $"{access} is null ? null : {cloneHelperName}({access}!, __sparse_clone_context)";
        }

        var cloned = CloneCollectionExpression(member, access + "!");
        return $"(object?){access} is null ? default : {cloned}";
    }

    private static string CloneCollectionExpression(SparseMemberModel member, string access)
    {
        var collection = member.Collection;
        if (collection.CloneKind == SparseCloneCollectionKind.Unsupported)
        {
            return access;
        }

        var elementType = collection.ElementType.Name;
        var elements = access;
        if (
            collection.ElementType.IsFragmentModel
            || collection.ElementType.PocoCloneHelperName is not null
        )
        {
            elements =
                $"global::System.Linq.Enumerable.Select({access}, item => {CloneValueExpression(collection.ElementType, "item")})";
        }

        if (collection.ValueType is not null)
        {
            if (collection.CloneKind == SparseCloneCollectionKind.PriorityQueue)
            {
                var priorityType = collection.ValueType.Value.Name;
                var elementSelector = CloneValueExpression(collection.ElementType, "item.Element");
                var prioritySelector = CloneValueExpression(collection.ValueType.Value, "item.Priority");
                var entries =
                    $"global::System.Linq.Enumerable.Select({access}.UnorderedItems, item => ({elementSelector}, {prioritySelector}))";
                return $"new global::System.Collections.Generic.PriorityQueue<{elementType}, {priorityType}>({entries}, {access}.Comparer)";
            }

            if (collection.CloneKind == SparseCloneCollectionKind.Dictionary)
            {
                var isConcreteDictionary =
                    collection.NamedTypeDefinition == "System.Collections.Generic.Dictionary<TKey, TValue>";
                var comparer = isConcreteDictionary ? access + ".Comparer" : null;
                var keySelector =
                    $"pair => {CloneValueExpression(collection.ElementType, "pair.Key")}";
                var valueSelector =
                    $"pair => {CloneValueExpression(collection.ValueType.Value, "pair.Value")}";
                return comparer is null
                    ? $"global::System.Linq.Enumerable.ToDictionary({access}, {keySelector}, {valueSelector})"
                    : $"global::System.Linq.Enumerable.ToDictionary({access}, {keySelector}, {valueSelector}, {comparer})";
            }

            if (collection.CloneKind == SparseCloneCollectionKind.ImmutableDictionary)
            {
                var keySelector =
                    $"pair => {CloneValueExpression(collection.ElementType, "pair.Key")}";
                var valueSelector =
                    $"pair => {CloneValueExpression(collection.ValueType.Value, "pair.Value")}";
                return $"global::System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary({access}, {keySelector}, {valueSelector}, {access}.KeyComparer, {access}.ValueComparer)";
            }

            return access;
        }

        return collection.CloneKind switch
        {
            SparseCloneCollectionKind.Array => $"global::System.Linq.Enumerable.ToArray({elements})",
            SparseCloneCollectionKind.List =>
                $"new global::System.Collections.Generic.List<{elementType}>({elements})",
            SparseCloneCollectionKind.Set => CloneSetExpression(collection, access, elements, elementType),
            SparseCloneCollectionKind.ImmutableSet =>
                CloneSetExpression(collection, access, elements, elementType),
            SparseCloneCollectionKind.Queue =>
                $"new global::System.Collections.Generic.Queue<{elementType}>({elements})",
            SparseCloneCollectionKind.Stack =>
                $"new global::System.Collections.Generic.Stack<{elementType}>(global::System.Linq.Enumerable.Reverse({elements}))",
            SparseCloneCollectionKind.ConcurrentQueue =>
                $"new global::System.Collections.Concurrent.ConcurrentQueue<{elementType}>({elements})",
            SparseCloneCollectionKind.ConcurrentStack =>
                $"new global::System.Collections.Concurrent.ConcurrentStack<{elementType}>(global::System.Linq.Enumerable.Reverse({elements}))",
            SparseCloneCollectionKind.BlockingCollection =>
                $"__CloneBlockingCollection({access}, {elements})",
            SparseCloneCollectionKind.LinkedList =>
                $"new global::System.Collections.Generic.LinkedList<{elementType}>({elements})",
            SparseCloneCollectionKind.SortedSet =>
                $"new global::System.Collections.Generic.SortedSet<{elementType}>({elements}, {access}.Comparer)",
            SparseCloneCollectionKind.ObservableCollection =>
                $"new global::System.Collections.ObjectModel.ObservableCollection<{elementType}>({elements})",
            SparseCloneCollectionKind.ReadOnlyCollection =>
                $"new global::System.Collections.ObjectModel.ReadOnlyCollection<{elementType}>(new global::System.Collections.Generic.List<{elementType}>({elements}))",
            SparseCloneCollectionKind.ImmutableArray =>
                $"{access}.IsDefault ? {access} : global::System.Collections.Immutable.ImmutableArray.CreateRange({elements})",
            SparseCloneCollectionKind.ImmutableList =>
                $"global::System.Collections.Immutable.ImmutableList.CreateRange({elements})",
            _ => access,
        };
    }

    private static string CloneSetExpression(
        SparseCollectionInfo collection,
        string access,
        string elements,
        string elementType
    )
    {
        var definition = collection.NamedTypeDefinition;
        return definition switch
        {
            "System.Collections.Generic.HashSet<T>" =>
                $"new global::System.Collections.Generic.HashSet<{elementType}>({elements}, {access}.Comparer)",
            "System.Collections.Generic.SortedSet<T>" =>
                $"new global::System.Collections.Generic.SortedSet<{elementType}>({elements}, {access}.Comparer)",
            "System.Collections.Immutable.ImmutableHashSet<T>" =>
                $"global::System.Collections.Immutable.ImmutableHashSet.CreateRange({access}.KeyComparer, {elements})",
            _ => $"new global::System.Collections.Generic.HashSet<{elementType}>({elements})",
        };
    }

    private static string BuildCollectionMerge(
        SparseMemberModel member,
        string lower,
        string higher
    )
    {
        var elementType = member.Collection.ElementType.Name;
        if (member.Collection.Kind == SparseCollectionKind.Set)
        {
            return $"{CollectionMerger}.MergeSet<{elementType}>({lower}, {higher})";
        }

        var combined = $"global::System.Linq.Enumerable.Concat({lower}, {higher})";
        if (member.MergeMode == 3)
        {
            combined = $"global::System.Linq.Enumerable.Distinct({combined})";
        }

        return member.Collection.Kind switch
        {
            SparseCollectionKind.List =>
                $"new global::System.Collections.Generic.List<{elementType}>({combined})",
            _ => $"global::System.Linq.Enumerable.ToArray({combined})",
        };
    }
}
