<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/providers/Configlue.Provider.Json/Configlue.Provider.Json.csproj" />
    <ProjectReference Include="../../src/resources/Configlue.Resource.Http/Configlue.Resource.Http.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="globalsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="localsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="policy.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
