<Project>
  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MSBuildTreatAllWarningsAsErrors>true</MSBuildTreatAllWarningsAsErrors>
    <RestoreTreatWarningsAsErrors>true</RestoreTreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <ConfiglueTooling
      Condition="'$(MSBuildProjectName)' == 'Configlue.Generator' or '$(MSBuildProjectName)' == 'Configlue.JsonSchema.MSBuild'"
      >true</ConfiglueTooling>
    <GenerateDocumentationFile Condition="'$(ConfiglueTooling)' != 'true'"
      >true</GenerateDocumentationFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/arika0093/Configlue</RepositoryUrl>
    <PackageProjectUrl>https://github.com/arika0093/Configlue</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PolyArgumentExceptions>true</PolyArgumentExceptions>
    <PolyUseEmbeddedAttribute>true</PolyUseEmbeddedAttribute>
    <ConfiglueNetStandard20 Condition="'$(TargetFramework)' == 'netstandard2.0'"
      >true</ConfiglueNetStandard20>
    <ConfiglueNetStandard
      Condition="'$(ConfiglueNetStandard20)' == 'true' or '$(TargetFramework)' == 'netstandard2.1'"
      >true</ConfiglueNetStandard>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.*" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CSharpier.MsBuild" Version="1.3.0" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.*" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup Condition="'$(ConfiglueTooling)' != 'true' and '$(ConfiglueUtility)' != 'true'">
    <Using Include="Configlue.Codecs" />
    <Using Include="Configlue.Migrations" />
    <Using Include="Configlue.Resources" />
    <Using Include="Configlue.Sources" />
    <Using Include="Configlue.Extensibility" />
    <Using Include="Configlue.State" />
    <Using Include="Configlue.Transformers" />
  </ItemGroup>
  <ItemGroup Condition="'$(ConfiglueNetStandard20)' == 'true' and '$(ConfiglueTooling)' != 'true'">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.12" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
  </ItemGroup>
  <ItemGroup Condition="'$(ConfiglueNetStandard)' == 'true' and '$(ConfiglueTooling)' != 'true'">
    <PackageReference Include="Polyfill" Version="11.4.1" PrivateAssets="all" />
    <PackageReference Include="System.Threading.Channels" Version="10.0.5" />
  </ItemGroup>
</Project>
