<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Configlue.Resource.Zip</AssemblyName>
    <RootNamespace>Configlue.Resource.Zip</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageDescription>ZIP archive entry resources for Configlue.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Configlue.Abstraction/Configlue.Abstraction.csproj" />
    <ProjectReference Include="../Configlue.Core/Configlue.Core.csproj" />
  </ItemGroup>
</Project>
