using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Configlue.Generator;

public sealed partial class ConfiglueGenerator
{
    private static string BuildSource(
        INamedTypeSymbol model,
        ImmutableArray<MemberModel> members,
        ImmutableArray<PreviousModelInfo> previousModels,
        CancellationToken cancellationToken
    )
    {
        var modelType = NonNullableTypeName(model);
        string generatedType;
        if (model.TypeKind == TypeKind.Struct)
        {
            generatedType = model.IsRecord ? "partial record struct " : "partial struct ";
        }
        else
        {
            generatedType = model.IsRecord ? "partial record class " : "partial class ";
        }
        var name = EscapeIdentifier(model.Name);
        var modelId = GetModelId(model, cancellationToken);
        var version = GetModelVersion(model, cancellationToken);
        var code = new IndentedStringBuilder(cancellationToken);
        code.AppendLine("// <auto-generated />");
        code.AppendLine("#nullable enable");
        if (!model.ContainingNamespace.IsGlobalNamespace)
        {
            code.Append("namespace ")
                .Append(model.ContainingNamespace.ToDisplayString())
                .AppendLine(";");
        }
        code.Append(generatedType)
            .Append(name)
            .Append(" : global::Configlue.IConfiglueDeepCloneable<")
            .Append(modelType)
            .Append(">, global::Configlue.IConfiglueModel<")
            .Append(modelType)
            .Append(", ")
            .Append(modelType)
            .Append(".Fragment>, global::Configlue.IConfiglueFacadeModel<")
            .Append(modelType)
            .AppendLine(">");
        code.AppendLine("{");
        AppendModelSchema(code, modelType, modelId, version, members);
        AppendFragmentSchema(code, modelType, modelId, version, members);
        AppendDeepClone(code, modelType, members);
        AppendPocoCloneHelpers(code, GetPocoCloneTypes(members, cancellationToken));
        AppendCollectionCloneHelpers(code);
        AppendFragment(code, modelType, members, previousModels);
        AppendModelFragmentBridge(code, modelType);
        AppendFacadeRuntimeBridge(code, modelType);
        AppendHistoricalDispatcherFactory(code, modelType, previousModels);
        code.AppendLine("}");
        return code.ToString();
    }

    private static void AppendCollectionCloneHelpers(IndentedStringBuilder code)
    {
        code.AppendLineAt(
            1,
            "private static global::System.Collections.Concurrent.BlockingCollection<T> __CloneBlockingCollection<T>(global::System.Collections.Concurrent.BlockingCollection<T> original, global::System.Collections.Generic.IEnumerable<T> items)"
        );
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "var queue = new global::System.Collections.Concurrent.ConcurrentQueue<T>(items);"
        );
        code.AppendLineAt(2, "var clone = original.BoundedCapacity > 0");
        code.AppendLineAt(
            3,
            "? new global::System.Collections.Concurrent.BlockingCollection<T>(queue, original.BoundedCapacity)"
        );
        code.AppendLineAt(
            3,
            ": new global::System.Collections.Concurrent.BlockingCollection<T>(queue);"
        );
        code.AppendLineAt(2, "if (original.IsAddingCompleted)");
        code.AppendLineAt(2, "{");
        code.AppendLineAt(3, "clone.CompleteAdding();");
        code.AppendLineAt(2, "}");
        code.AppendLineAt(2, "return clone;");
        code.AppendLineAt(1, "}");
    }

    private static void AppendHistoricalDispatcherFactory(
        IndentedStringBuilder code,
        string modelType,
        ImmutableArray<PreviousModelInfo> previousModels
    )
    {
        if (previousModels.IsEmpty)
        {
            return;
        }

        var parameters = new List<string>();
        var parameterDocs = new List<string>();
        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = GetModelVersion(previousModel, code.CancellationToken);
            var previousType = NonNullableTypeName(previousModel) + ".Fragment";
            var codecName = "previousV" + version + "Codec";
            parameters.Add(
                "        global::Configlue.IStateCodec<" + previousType + "> " + codecName
            );
            parameterDocs.Add(
                "/// <param name=\""
                    + codecName
                    + "\">The codec for historical schema version "
                    + version
                    + ".</param>"
            );
        }

        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = GetModelVersion(previousModel, code.CancellationToken);
            var previousType = NonNullableTypeName(previousModel) + ".Fragment";
            var migrationName = "migrateV" + version;
            parameters.Add(
                "        global::System.Func<"
                    + previousType
                    + ", "
                    + modelType
                    + ".Fragment>? "
                    + migrationName
                    + " = null"
            );
            parameterDocs.Add(
                "/// <param name=\""
                    + migrationName
                    + "\">An optional custom migration from schema version "
                    + version
                    + "; compatible same-name members are transferred by default.</param>"
            );
        }

        code.AppendLineAt(
            1,
            "/// <summary>Creates a closed, version-aware decoder table for the declared historical fragment types.</summary>"
        );
        foreach (var parameterDoc in parameterDocs)
        {
            code.AppendLineAt(1, parameterDoc);
        }
        var accessibility = previousModels.Any(static previous =>
            previous.Model.DeclaredAccessibility != Accessibility.Public
        )
            ? "internal"
            : "public";
        code.AppendIndent(1)
            .Append(accessibility)
            .Append(" static global::Configlue.StateSchemaDispatcher<")
            .Append(modelType)
            .AppendLine(".Fragment> CreateSchemaDispatcher(");
        for (var index = 0; index < parameters.Count; index++)
        {
            code.Append(parameters[index]);
            if (index < parameters.Count - 1)
            {
                code.AppendLine(",");
            }
        }

        code.AppendLineAt(1, ")");
        code.AppendLineAt(1, "{");
        code.AppendIndent(2)
            .Append("var dispatcher = new global::Configlue.StateSchemaDispatcher<")
            .Append(modelType)
            .AppendLine(".Fragment>(ConfiglueSchema.ToMetadata());");
        foreach (var previousModel in previousModels.Select(static previous => previous.Model))
        {
            var version = GetModelVersion(previousModel, code.CancellationToken);
            var previousType = NonNullableTypeName(previousModel);
            code.AppendIndent(2)
                .Append("dispatcher.Add<")
                .Append(previousType)
                .Append(".Fragment>(")
                .Append(previousType)
                .Append(".FragmentSchema.ToMetadata(), previousV")
                .Append(version)
                .Append("Codec, migrateV")
                .Append(version)
                .Append(" ?? (static value => ")
                .Append(modelType)
                .AppendLine(".Fragment.FromPrevious(value)));");
        }

        code.AppendLineAt(2, "return dispatcher;");
        code.AppendLineAt(1, "}");
    }

    private static void AppendModelSchema(
        IndentedStringBuilder code,
        string modelType,
        string modelId,
        int version,
        ImmutableArray<MemberModel> members
    )
    {
        code.AppendIndent(1)
            .Append(
                "public static global::Configlue.ConfiglueModelSchema ConfiglueSchema { get; } = new(typeof("
            )
            .Append(modelType)
            .Append("), ")
            .Append(SymbolDisplay.FormatLiteral(modelId, true))
            .Append(", ")
            .Append(version)
            .AppendLine(", new global::Configlue.ConfiglueMemberSchema[]");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            code.AppendIndent(2)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append(NonNullableTypeName(member.ChildModel ?? member.Property.Type))
                .Append("), global::Configlue.MergeMode.")
                .Append(MergeModeName(member.MergeMode))
                .Append(", static value => ((")
                .Append(modelType)
                .Append(")value).")
                .Append(EscapeIdentifier(member.Property.Name))
                .Append(", ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(NonNullableTypeName(member.ChildModel))
                    .Append(".ConfiglueSchema");
            }

            code.Append(", ")
                .Append(CollectionValueFactory(member))
                .Append(", ")
                .Append(
                    GetEnvironmentVariableName(member.Property, code.CancellationToken) is { } name
                        ? SymbolDisplay.FormatLiteral(name, true)
                        : "null"
                )
                .Append(", ")
                .Append(
                    member.MergeStrategyType is null
                        ? "null"
                        : "Fragment.__configlue_merge_strategy_" + member.Id
                )
                .AppendLine("),");
        }

        code.AppendIndent(1)
            .Append("}, static () => ")
            .Append(modelType)
            .AppendLine(".Fragment.Empty);");
        code.AppendLineAt(
            1,
            "public static global::Configlue.ConfiglueModelSchema GetConfiglueSchema() => ConfiglueSchema;"
        );
    }

    private static string CollectionValueFactory(MemberModel member)
    {
        if (member.MergeStrategyType is not null || member.MergeMode is not (2 or 3))
        {
            return "null";
        }

        var elementType = TypeName(member.Collection.ElementType);
        var values = $"global::System.Linq.Enumerable.Cast<{elementType}>(values)";
        return member.Collection.Kind switch
        {
            CollectionKind.Array =>
                $"static values => global::System.Linq.Enumerable.ToArray({values})",
            CollectionKind.List =>
                $"static values => new global::System.Collections.Generic.List<{elementType}>({values})",
            CollectionKind.Set =>
                $"static values => new global::System.Collections.Generic.HashSet<{elementType}>({values})",
            _ => "null",
        };
    }

    private static void AppendFragmentSchema(
        IndentedStringBuilder code,
        string modelType,
        string modelId,
        int version,
        ImmutableArray<MemberModel> members
    )
    {
        code.AppendIndent(1)
            .Append(
                "public static global::Configlue.ConfiglueModelSchema FragmentSchema { get; } = new(typeof("
            )
            .Append(modelType)
            .Append("), ")
            .Append(SymbolDisplay.FormatLiteral(modelId, true))
            .Append(", ")
            .Append(version)
            .AppendLine(", new global::Configlue.ConfiglueMemberSchema[]");
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            var valueType = member.ChildModel is null
                ? NonNullableTypeName(member.Property.Type)
                : NonNullableTypeName(member.ChildModel) + ".Fragment";
            code.AppendIndent(2)
                .Append("new(")
                .Append(member.Id)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(member.Property.Name, true))
                .Append(", typeof(")
                .Append(valueType)
                .Append("), global::Configlue.MergeMode.")
                .Append(MergeModeName(member.MergeMode))
                .Append(", null, ");
            if (member.ChildModel is null)
            {
                code.Append("null");
            }
            else
            {
                code.Append("static () => ")
                    .Append(NonNullableTypeName(member.ChildModel))
                    .Append(".FragmentSchema");
            }

            code.Append(", null, null, ")
                .Append(
                    member.MergeStrategyType is null
                        ? "null"
                        : "Fragment.__configlue_merge_strategy_" + member.Id
                );
            code.AppendLine("),");
        }

        code.AppendIndent(1)
            .Append("}, static () => ")
            .Append(modelType)
            .AppendLine(".Fragment.Empty);");
    }

    private static void AppendDeepClone(
        IndentedStringBuilder code,
        string modelType,
        ImmutableArray<MemberModel> members
    )
    {
        code.AppendIndent(1).Append("public ").Append(modelType).AppendLine(" DeepClone()");
        code.AppendLineAt(1, "{");
        code.AppendLineAt(
            2,
            "var __configlue_clone_context = new global::System.Collections.Generic.Dictionary<object, object>(global::System.Collections.Generic.ReferenceEqualityComparer.Instance);"
        );
        code.AppendIndent(2).Append("return new ").Append(modelType).AppendLine();
        code.AppendLineAt(1, "{");
        foreach (var member in members)
        {
            code.AppendIndent(2)
                .Append(EscapeIdentifier(member.Property.Name))
                .Append(" = ")
                .Append(
                    CloneModelExpression(
                        member,
                        "this." + EscapeIdentifier(member.Property.Name),
                        code.CancellationToken
                    )
                )
                .AppendLine(",");
        }

        code.AppendLineAt(1, "};");
        code.AppendLineAt(1, "}");
    }

    private static void AppendPocoCloneHelpers(
        IndentedStringBuilder code,
        ImmutableArray<INamedTypeSymbol> pocoTypes
    )
    {
        foreach (var pocoType in pocoTypes)
        {
            var typeName = NonNullableTypeName(pocoType);
            var helperName =
                "__Clone_" + GetStableTypeHash(pocoType.ToDisplayString(), code.CancellationToken);
            code.AppendIndent(1)
                .Append("private static ")
                .Append(typeName)
                .Append(' ')
                .Append(helperName)
                .Append('(')
                .Append(typeName)
                .AppendLine(
                    " value, global::System.Collections.Generic.Dictionary<object, object> __configlue_clone_context)"
                );
            code.AppendLineAt(1, "{");
            code.AppendLineAt(
                2,
                "if (__configlue_clone_context.TryGetValue(value, out var existing)) return ("
                    + typeName
                    + ")existing;"
            );
            code.AppendIndent(2).Append("var clone = new ").Append(typeName).AppendLine("();");
            code.AppendLineAt(2, "__configlue_clone_context.Add(value, clone);");
            foreach (var member in GetMembers(pocoType, code.CancellationToken))
            {
                var name = EscapeIdentifier(member.Property.Name);
                code.AppendIndent(2)
                    .Append("clone.")
                    .Append(name)
                    .Append(" = ")
                    .Append(CloneModelExpression(member, "value." + name, code.CancellationToken))
                    .AppendLine(";");
            }
            code.AppendLineAt(2, "return clone;");
            code.AppendLineAt(1, "}");
        }
    }

    private static void AppendModelFragmentBridge(IndentedStringBuilder code, string modelType)
    {
        code.AppendIndent(1)
            .Append("public static Fragment ToFragment(")
            .Append(modelType)
            .AppendLine(" value) => Fragment.From(value);");
        code.AppendIndent(1)
            .Append("public static Fragment Diff(")
            .Append(modelType)
            .Append(" before, ")
            .Append(modelType)
            .AppendLine(" after) => Fragment.Diff(before, after);");
        code.AppendIndent(1)
            .Append("public static ")
            .Append(modelType)
            .AppendLine(" FromFragment(Fragment value) => value.ToModel();");
    }

    private static void AppendFacadeRuntimeBridge(IndentedStringBuilder code, string modelType)
    {
        code.AppendIndent(1)
            .Append("public static global::Configlue.IWritableOptions<")
            .Append(modelType)
            .AppendLine("> CreateConfiglueRuntime(");
        code.AppendLineAt(
            2,
            "global::Configlue.ConfiglueModelBuilder<" + modelType + "> configuration,"
        );
        code.AppendLineAt(2, "global::System.IServiceProvider? serviceProvider,");
        code.AppendLineAt(2, "global::System.Action<global::System.IDisposable> ownResource)");
        code.AppendIndent(2)
            .Append("=> new global::Configlue.ConfiglueOptions<")
            .Append(modelType)
            .Append(", ")
            .Append(modelType)
            .AppendLine(".Fragment>(");
        code.AppendLineAt(
            3,
            "configuration.BuildSources<"
                + modelType
                + ".Fragment>("
                + modelType
                + ".ConfiglueSchema, serviceProvider, ownResource),"
        );
        code.AppendLineAt(3, "configuration.WriteRoute,");
        code.AppendLineAt(3, "configuration.WritePlan,");
        code.AppendLineAt(
            3,
            "configuration.GetMigrations<" + modelType + ".Fragment>(serviceProvider),"
        );
        code.AppendLineAt(3, "configuration.GetValidators(serviceProvider),");
        code.AppendLineAt(3, "configuration.ValidateDataAnnotations,");
        code.AppendLineAt(3, "configuration.OnChangeDebounce,");
        code.AppendLineAt(3, "configuration.OptionsName,");
        code.AppendLineAt(3, "configuration.GetLogger(serviceProvider),");
        code.AppendLineAt(3, "configuration.CloneStrategy);");
        code.AppendIndent(1)
            .Append("public static global::Configlue.IConfiglueProfiledOptions<")
            .Append(modelType)
            .AppendLine("> CreateConfiglueProfileManager(");
        code.AppendLineAt(
            2,
            "global::Configlue.IConfiglueOptionsRegistry<" + modelType + "> registry,"
        );
        code.AppendLineAt(
            2,
            "global::Configlue.StateSource<global::Configlue.ConfiglueProfileCatalog> catalogSource,"
        );
        code.AppendLineAt(2, "string defaultProfileName)");
        code.AppendIndent(2)
            .Append("=> new global::Configlue.ConfiglueProfiledOptions<")
            .Append(modelType)
            .Append(", ")
            .Append(modelType)
            .AppendLine(".Fragment>(registry, catalogSource, defaultProfileName);");
    }
}
