<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Configlue.Extensions.DI</AssemblyName>
    <RootNamespace>Configlue</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageDescription>Dependency injection registration for Configlue options.</PackageDescription>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Configlue.Extension.MSOptions" />
    <ProjectReference Include="../Configlue.Abstraction/Configlue.Abstraction.csproj" />
    <ProjectReference Include="../Configlue.Core/Configlue.Core.csproj" />
    <ProjectReference Include="../Configlue.Provider.Json/Configlue.Provider.Json.csproj" />
    <ProjectReference Include="../Configlue.Resource.Http/Configlue.Resource.Http.csproj" />
    <PackageReference
      Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="10.0.0"
    />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
  </ItemGroup>
</Project>
